//! Public crate facade re-exports grouped by owner surface.

pub use crate::{
    bpmn_callable_api::{
        BpmnCallActivityBinding, BpmnCallableBindingExecutionPolicy, BpmnCallableDataRef,
        BpmnCallableDefinition, BpmnCallableIoBinding, BpmnCallableKind, BpmnCallableRegistry,
    },
    bpmn_collaboration_api::{
        BpmnCollaborationExecutionPolicy, BpmnCollaborationHostBoundary,
        BpmnCollaborationHostEnvelope, BpmnCollaborationIntent, BpmnCollaborationRuntimeScope,
        BpmnCorrelationKeyIntent, BpmnCorrelationKeyScope, BpmnCorrelationPropertyBindingIntent,
        BpmnCorrelationPropertyIntent, BpmnCorrelationPropertyRetrievalIntent,
        BpmnEventDeduplicationPolicy, BpmnMessageFlowIntent, BpmnParticipantIntent,
        BpmnParticipantMultiplicityIntent, BpmnProcessCorrelationSubscriptionIntent,
    },
    bpmn_conformance_api::{
        BpmnConformanceEntry, BpmnConformanceStatus, bpmn_conformance_registry,
    },
    bpmn_model_api::{
        BpmnAssociationSnapshot, BpmnBoundsSnapshot, BpmnCategorySnapshot,
        BpmnCategoryValueSnapshot, BpmnChoreographyActivitySnapshot, BpmnCollaborationSnapshot,
        BpmnConversationAssociationSnapshot, BpmnConversationLinkSnapshot,
        BpmnConversationNodeSnapshot, BpmnCorrelationKeySnapshot,
        BpmnCorrelationPropertyBindingSnapshot, BpmnCorrelationPropertySnapshot,
        BpmnCorrelationSubscriptionSnapshot, BpmnDataAssociationAssignmentSnapshot,
        BpmnDataAssociationExpressionSnapshot, BpmnDataAssociationSnapshot,
        BpmnDataInputOutputSnapshot, BpmnDataObjectReferenceSnapshot, BpmnDataObjectSnapshot,
        BpmnDataStateSnapshot, BpmnDataStoreReferenceSnapshot, BpmnDataStoreSnapshot,
        BpmnDiagramSnapshot, BpmnDocumentSnapshot, BpmnEdgeSnapshot, BpmnEndPointSnapshot,
        BpmnErrorSnapshot, BpmnEscalationSnapshot, BpmnExtensionSnapshot,
        BpmnFlowElementMetadataSnapshot, BpmnFontSnapshot, BpmnGlobalTaskSnapshot,
        BpmnGroupSnapshot, BpmnImportSnapshot, BpmnInputSetSnapshot, BpmnInterfaceSnapshot,
        BpmnIoBindingSnapshot, BpmnIoSpecificationSnapshot, BpmnItemDefinitionSnapshot,
        BpmnLabelSnapshot, BpmnLabelStyleSnapshot, BpmnLaneSetSnapshot, BpmnLaneSnapshot,
        BpmnMessageFlowAssociationSnapshot, BpmnMessageFlowSnapshot, BpmnMessageSnapshot,
        BpmnOperationSnapshot, BpmnOutputSetSnapshot, BpmnParticipantAssociationSnapshot,
        BpmnParticipantMultiplicitySnapshot, BpmnParticipantSnapshot, BpmnPartnerEntitySnapshot,
        BpmnPartnerRoleSnapshot, BpmnPlaneSnapshot, BpmnProcessPropertySnapshot,
        BpmnProcessSnapshot, BpmnRelationshipSnapshot, BpmnResourceParameterBindingSnapshot,
        BpmnResourceParameterSnapshot, BpmnResourceRoleSnapshot, BpmnResourceSnapshot,
        BpmnRootSnapshot, BpmnShapeSnapshot, BpmnSignalSnapshot, BpmnTextAnnotationSnapshot,
        BpmnWaypointSnapshot,
    },
    bpmn_parse_api::{
        BpmnBundleSnapshot, BpmnParseOptions, BpmnSourceFile, parse_bpmn_bundle, parse_bpmn_package,
    },
    bpmn_snapshot_api::snapshot_bpmn_source,
    checkpoint_api::{
        BPMN_CHECKPOINT_FORMAT_VERSION, BpmnCheckpointEnvelope, BpmnCheckpointInstanceId,
        decode_checkpoint_json, encode_checkpoint_json, lease_key, state_key,
    },
    dmn_api::{
        DmnAssociationSnapshot, DmnBindingKind, DmnBoundsSnapshot,
        DmnBusinessKnowledgeModelDefinition, DmnBusinessKnowledgeModelSnapshot,
        DmnComparisonOperator, DmnContextEntry, DmnContextExpression, DmnDateComparison,
        DmnDateRange, DmnDateRangeBound, DmnDateTimeComparison, DmnDateTimeRange,
        DmnDateTimeRangeBound, DmnDecisionDefinition, DmnDecisionRef, DmnDecisionServiceDefinition,
        DmnDecisionServiceDividerLineSnapshot, DmnDecisionServiceReference,
        DmnDecisionServiceSnapshot, DmnDecisionSnapshot, DmnDecisionTable, DmnDecisionTableInput,
        DmnDefinitionsId, DmnDiagramSnapshot, DmnDmndiSnapshot, DmnDocumentSnapshot,
        DmnDurationComparison, DmnDurationRange, DmnDurationRangeBound, DmnEdgeSnapshot,
        DmnElementCollectionSnapshot, DmnEvaluationRequest, DmnEvaluationResult,
        DmnFunctionDefinitionLiteralSnapshot, DmnFunctionDefinitionParameterSnapshot,
        DmnFunctionDefinitionSnapshot, DmnGroupSnapshot, DmnHitPolicy, DmnImportDefinition,
        DmnImportDefinitionInput, DmnImportSourceBinding, DmnInformationRequirementReference,
        DmnInputClause, DmnInputClauseInput, DmnInputDataDefinition, DmnInputDataSnapshot,
        DmnInputEntry, DmnInvocation, DmnInvocationBinding, DmnInvocationBindingSnapshot,
        DmnInvocationLiteralSnapshot, DmnInvocationParameter, DmnInvocationParameterSnapshot,
        DmnInvocationSnapshot, DmnItemComponentSnapshot, DmnItemDefinitionSnapshot,
        DmnKnowledgeRequirementReference, DmnKnowledgeSourceSnapshot, DmnLabelSnapshot,
        DmnListExpression, DmnLiteralExpression, DmnModelNamespaceUri, DmnNumericComparison,
        DmnNumericRange, DmnNumericRangeBound, DmnOrganizationUnitSnapshot, DmnOutputClause,
        DmnOutputEntry, DmnPerformanceIndicatorSnapshot, DmnRangeBoundInclusivity,
        DmnRelationColumn, DmnRelationExpression, DmnRelationRow, DmnRequirementReferenceSnapshot,
        DmnRootSnapshot, DmnRule, DmnShapeSnapshot, DmnSourceDefinition, DmnSourceDefinitionInput,
        DmnSourceFile, DmnSourceId, DmnTextAnnotationSnapshot, DmnTimeComparison, DmnTimeRange,
        DmnTimeRangeBound, DmnVariableSnapshot, DmnWaypointSnapshot, evaluate_dmn_decision,
        parse_dmn_decision, parse_dmn_decisions, snapshot_dmn_source,
    },
    error::{
        BpmnEngineError, BpmnErrorId, BpmnErrorKind, BpmnErrorTokenId,
        BpmnPendingHostWorkIdentityMismatch,
    },
    host_bridge_api::BpmnHostBridge,
    host_types_api::{
        BpmnHostActivityId, BpmnHostInstanceId, BpmnHostProcessId, BpmnHostTokenId, BpmnHostWorkId,
        BusinessRuleTaskOutcome, BusinessRuleTaskRequest, EventPollOutcome, EventPollRequest,
        HostBridgeError, ManualTaskOutcome, ManualTaskRequest, ParallelMultiInstanceContext,
        PendingHostWorkRequest, PendingHostWorkResult, RepeatExecutionContext, ScriptTaskOutcome,
        ScriptTaskRequest, SendTaskOutcome, SendTaskRequest, SequentialMultiInstanceContext,
        ServiceTaskOutcome, ServiceTaskRequest, TaskOutcome, TaskRequest, UserTaskOutcome,
        UserTaskRequest,
    },
    ir_data_api::BpmnDataObjectBindingSpec,
    ir_edge_api::BpmnEdgeSpec,
    ir_event_api::{BpmnEventKind, BpmnEventSpec, BpmnTimerKind, BpmnTimerSpec},
    ir_index_api::{BpmnIndexRange, BpmnNodeIndex},
    ir_node_api::{
        BpmnGatewayKind, BpmnHumanTaskAssignmentSpec, BpmnHumanTaskChoiceSpec,
        BpmnHumanTaskFormSpec, BpmnHumanTaskFreeTextSpec, BpmnHumanTaskResourceRoleSpec,
        BpmnLaneMembershipSpec, BpmnNodeKind, BpmnNodeSpec, BpmnScriptTaskSpec, BpmnSubProcessKind,
        BpmnTaskInputBinding, BpmnTaskInputSource, BpmnTaskIoSpec, BpmnTaskOutputBinding,
    },
    ir_package_api::BpmnPackage,
    ir_process_compensation::BpmnCompensationHandlerSpec,
    ir_process_key::ProcessKey,
    ir_process_spec::{BpmnProcessSpec, BpmnProcessSpecInput},
    ir_repeat_api::{
        BpmnMultiInstanceDataBindingSpec, BpmnParallelMultiInstanceSpec, BpmnRepeatSpec,
        BpmnSequentialMultiInstanceSpec, BpmnStandardLoopSpec,
    },
    lint_api::{
        LintDomain, LintIssue, LintIssueInput, LintReport, LintSeverity, LintSourceDiagnostic,
        LintSourceSpan, lint_bpmn_source, lint_dmn_source,
    },
    repeat_condition_api::{GatewayConditionSummary, parse_gateway_condition_summary},
    runtime_advance_api::{BpmnAdvanceOutcome, advance_instance},
    runtime_claim_api::{
        BpmnHumanTaskClaimedAtMs, BpmnHumanTaskReleasedAtMs, PendingHumanTaskClaimInput,
        PendingHumanTaskClaimOutcome, PendingHumanTaskClaimRequest, PendingHumanTaskReleaseInput,
        PendingHumanTaskReleaseOutcome, PendingHumanTaskReleaseRequest, claim_pending_human_task,
        release_pending_human_task,
    },
    runtime_dispatch_api::{PendingHostWork, PendingHostWorkClaim, PendingHostWorkKind},
    runtime_frontier_api::{
        BpmnFrontierEntry, BpmnFrontierEntryStatus, BpmnFrontierExecutionBatch,
        BpmnFrontierExecutionProposal, BpmnFrontierExecutionStep, BpmnFrontierParallelJoinMerge,
        BpmnFrontierPlan, BpmnFrontierPlanAction, BpmnFrontierProposalSet, BpmnFrontierSnapshot,
        collect_frontier_proposals, merge_frontier_execution_steps, plan_frontier_step,
        reduce_frontier_plan, snapshot_frontier,
    },
    runtime_host_dispatch_api::{
        build_pending_host_work_request, build_pending_host_work_requests,
    },
    runtime_instance_api::{
        BpmnExecutionTraceEvent, BpmnExecutionTraceEventKind, BpmnHumanTaskLifecycleEvent,
        BpmnHumanTaskLifecycleEventKind, BpmnInstanceInit, BpmnInstanceState, BpmnProcessId,
        CallActivityFrame, EventCompetitionState, InstanceLifecycle, NodeRuntimeState,
        NodeRuntimeStatus, SuspendReason, create_instance,
    },
    runtime_join_api::JoinRuntimeState,
    runtime_repeat_api::{
        MultiInstanceCollectionKey, MultiInstanceCollectionKind, MultiInstanceCollectionSlot,
        MultiInstanceDataRuntimeState, MultiInstanceOutputCollectionState,
        ParallelMultiInstanceIterationState, ParallelMultiInstanceState,
        SequentialMultiInstanceState, StandardLoopState,
    },
    runtime_resume_api::{
        BpmnHostWorkCompletedAtMs, BpmnHostWorkTokenId, PendingHostWorkApplyInput,
        apply_pending_host_work_result,
    },
    runtime_token_api::{InclusiveJoinHint, TokenRecord},
    runtime_wait_api::{
        WaitKind, WaitRegistration, apply_event_poll_outcome, build_event_poll_request,
    },
};

#[cfg(feature = "valkey")]
pub use crate::checkpoint_api::{
    delete_checkpoint, delete_checkpoint_as_owner, load_checkpoint, release_checkpoint_lease,
    renew_checkpoint_lease, save_checkpoint, save_checkpoint_as_owner,
    try_acquire_checkpoint_lease,
};
