"""Shared benchmark payload builders for document extract perf tests."""

from __future__ import annotations


def pdf_ocr_milestone_result(
    *,
    fixture: str = "ocr-positive-pdf",
    attachment_class: str = "pdf",
    force_ms: float = 43_917.25,
    shard_cache_reuse_ms: float = 144.232,
    shard_cache_reuse_scheduler_ms: float | None = 144.232,
    resources_rows: int = 21,
    structure_rows: int = 21,
    ocr_page_blocks: int = 21,
    ocr_region_blocks: int = 0,
    bbox_blocks: int = 21,
    metrics_rows: int = 21,
    metrics_result_chars: int = 103_984,
) -> dict[str, object]:
    return {
        "fixture": fixture,
        "source": "/fixtures/2604.17337.pdf",
        "attachmentClass": attachment_class,
        "forceRefreshMs": force_ms,
        "forceErrorRows": 0,
        "shardCacheReuseForceMs": shard_cache_reuse_ms,
        "shardCacheReuseErrorRows": 0,
        "shardCacheReuseMetricsRustSchedulerElapsedMs": shard_cache_reuse_scheduler_ms,
        "shardCacheReuseHybridPageOcrTimingPhaseElapsedMs": {
            "regionMaterialize": max(shard_cache_reuse_ms - 10.0, 0.0),
            "ocrScheduler": shard_cache_reuse_scheduler_ms,
            "total": shard_cache_reuse_ms,
        },
        "forceHybridPageOcrTimingSchedulerTraceSummary": {
            "sourceRangeChunkCount": 3,
            "sourceRangeShardCount": 21,
            "sourceRangeTextCharCount": metrics_result_chars,
            "sourceRangeLatencyMsMax": 19_327.0,
            "sourceRangeQueueWaitMsMax": 3.0,
            "sourceRangeDispatchStartMsMin": 4.0,
            "sourceRangeDispatchEndMsMax": 19_331.0,
            "sourceRangeLongestPageStart": 0,
            "sourceRangeLongestPageEnd": 6,
            "sourceRangeLongestShardCount": 7,
            "sourceRangeLongestQueueWaitMs": 3.0,
            "sourceRangeLongestDispatchStartMs": 4.0,
            "sourceRangeLongestDispatchEndMs": 19_331.0,
            "sourceRangeLongestTextCharCount": 48_879,
        },
        "artifactRegistryReuseErrorRows": 0,
        "cacheHitP95Ms": 11.921,
        "cacheErrorRows": 0,
        "cacheSpeedup": 10.0,
        "requestCount": 1,
        "arrowIpcBytes": 117_128,
        "totalRows": resources_rows,
        "duplicateMissConverterCalls": 0,
        "resourcesRows": resources_rows,
        "structureRows": structure_rows,
        "structureOcrPageBlocks": ocr_page_blocks,
        "structureOcrRegionBlocks": ocr_region_blocks,
        "structureBboxBlocks": bbox_blocks,
        "structureReadingOrderSorted": True,
        "structureOrderStable": True,
        "structureOrderMismatchCount": 0,
        "structureParityErrorCount": 0,
        "metricsRows": metrics_rows,
        "metricsResultChars": metrics_result_chars,
        "metricsBboxCount": bbox_blocks,
        "metricsRustSchedulerElapsedMs": 144.232,
        "documentTimingTotalElapsedMs": force_ms,
        "documentTimingOverheadMs": 0.0,
        "documentTimingPhaseElapsedMs": {"doclingConvert": force_ms - 100.0},
        "artifactErrorCount": 0,
        "rustJobsStatusSummary": {},
    }


def hosted_vlm_promotion_payload(
    benchmark: object,
    *,
    rust_pdf_ocr_profile_planner: str = "hosted-vlm-risk-window",
    rust_pdf_hosted_vlm_region_planner: str = "profile-risk-window",
    force_ms: float = 10_000.0,
    shard_cache_reuse_ms: float = 144.232,
    shard_cache_reuse_scheduler_ms: float | None = 144.232,
    metrics_result_chars: int = 109_412,
    request_count: int = 3,
    success_count: int = 3,
    failure_count: int = 0,
    parse_error_count: int = 0,
    ocr_region_blocks: int = 3,
    region_atlas_mode: str = "disabled",
    scaffold_mode: str = "disabled",
    scaffold_applied_count: int = 0,
    scaffold_validation_failure_count: int = 0,
) -> dict[str, object]:
    result = pdf_ocr_milestone_result(
        force_ms=force_ms,
        shard_cache_reuse_ms=shard_cache_reuse_ms,
        shard_cache_reuse_scheduler_ms=shard_cache_reuse_scheduler_ms,
        resources_rows=21 + ocr_region_blocks,
        structure_rows=21 + ocr_region_blocks,
        ocr_page_blocks=21,
        ocr_region_blocks=ocr_region_blocks,
        bbox_blocks=21 + ocr_region_blocks,
        metrics_rows=21 + ocr_region_blocks,
        metrics_result_chars=metrics_result_chars,
    )
    summary = benchmark.summarize_results([result])
    return {
        "rustPdfOcrProfilePlanner": rust_pdf_ocr_profile_planner,
        "rustPdfHostedVlmRegionPlanner": rust_pdf_hosted_vlm_region_planner,
        "summary": summary,
        "hostedVlmOcr": {
            "provider": "openrouter",
            "openRouterModel": "baidu/qianfan-ocr-fast:free",
            "openRouterApiKeyConfigured": True,
            "regionAtlasMode": region_atlas_mode,
            "scaffoldMode": scaffold_mode,
            "requestSummary": {
                "requestCount": request_count,
                "successCount": success_count,
                "failureCount": failure_count,
                "parseErrorCount": parse_error_count,
                "regionShardCount": ocr_region_blocks,
                "scaffoldAppliedCount": scaffold_applied_count,
                "scaffoldValidationFailureCount": scaffold_validation_failure_count,
                "scaffoldJsonCharCountTotal": 800,
                "canonicalMarkdownCharCountTotal": 640,
                "latencyMsP95": 10_000.0,
                "sourcePixelAreaTotal": 8_734_917,
            },
        },
    }


def distinct_miss_summary_result(benchmark: object) -> dict[str, object]:
    """Build a result row that covers distinct miss and attachment summaries."""

    return {
        "fixture": "small-md",
        "totalRows": 10,
        "forceErrorRows": 0,
        "cacheErrorRows": 0,
        "shardCacheReuseEnabled": True,
        "shardCacheReuseForceMs": 42.0,
        "shardCacheReuseErrorRows": 0,
        "artifactRegistryReuseEnabled": True,
        "artifactRegistryReuseForceMs": 9.0,
        "artifactRegistryReuseErrorRows": 0,
        "requestCount": 2,
        "arrowIpcBytes": 1024,
        "cacheSpeedup": 2.0,
        "duplicateMissConverterCalls": None,
        "rustJobsStatusSummary": benchmark.summarize_rust_jobs_status_samples([]),
        "rows": 5,
        "forceRefreshMs": 10.0,
        "cacheHitP50Ms": 1.0,
        "cacheHitP95Ms": 2.0,
        "wallTimeMs": 3.0,
        "cacheMaxRssKb": None,
        "rustJobsMaxQueuedJobs": None,
        "rustJobsMaxRunningJobs": None,
        "rustJobsMinAvailableConversionPermits": None,
        "metricsRows": 2,
        "metricsResultChars": 80,
        "metricsBboxCount": 2,
        "metricsRustSchedulerElapsedMs": 12.0,
        "documentTimingRows": 3,
        "documentTimingTotalElapsedMs": 30.0,
        "documentTimingOverheadMs": 8.0,
        "documentTimingPhaseElapsedMs": {"doclingConvert": 20.0, "total": 30.0},
        "forceHybridPageOcrTimingPageRangeDoclingFallbackChunkSummary": {
            "chunkCount": 1,
            "elapsedMsTotal": 19_327.0,
            "elapsedMsMax": 19_327.0,
            "elapsedMsMin": 19_327.0,
            "documentExtractProfileCounts": {"structure-text": 1},
        },
        "structureParityChecked": True,
        "structureParityPassed": True,
        "structureParityErrorCount": 0,
        "structureOrderStable": True,
        "structureOrderMismatchCount": 0,
        "artifactReports": [_distinct_artifact_report()],
    }


def distinct_miss_report() -> dict[str, object]:
    """Build a distinct cold miss burst report fixture."""

    return {
        "enabled": True,
        "fixtures": ["distinct-01", "distinct-02"],
        "fixtureCount": 2,
        "requestCount": 2,
        "converterCalls": 2,
        "errorRows": 0,
        "wallTimeMs": 25.0,
        "rustJobsStatusSummary": {
            "sampleCount": 3,
            "maxQueuedJobs": 2,
            "maxRunningJobs": 2,
            "maxInProcessRunningConversions": 2,
            "maxInProcessScheduledJobs": 2,
            "minAvailableConversionPermits": 2,
            "maxRunningConversions": 4,
            "lastConversionDurationMs": 20,
            "maxConversionDurationMs": 21,
        },
    }


def markdown_report_payload(
    benchmark: object,
    *,
    summary: dict[str, object],
    result: dict[str, object],
    distinct_report: dict[str, object],
) -> dict[str, object]:
    """Build a full markdown report payload fixture."""

    return {
        "schema": benchmark.REPORT_SCHEMA,
        "mode": "fixture",
        "endpoint": "http://127.0.0.1:50052",
        "rustRestEndpoint": None,
        "iterations": 1,
        "concurrency": 1,
        "flightMode": "async",
        "waitMs": 0,
        "pdfOcrWorker": "skip",
        "pdfOcrWorkers": "auto",
        "documentExtractPrewarmPageRanges": "rust-page-range-chunk-plan",
        "documentExtractPrewarmPageRangesResolved": "1:3,4:4,5:6,7:9",
        "rustPdfDoclingPageRangeHedgeDelayMs": 7000,
        "rustPdfDoclingPageRangeStructureCostBudget": 2400,
        "rustPdfDoclingTextShortcutPromotion": "disabled",
        "rustPdfOcrWorkers": None,
        "rustPdfOcrSourceRangeWorkers": "2",
        "structureBaselineRoot": "/tmp/baselines",
        "pdfOcrProfile": "skip",
        "shardCacheReuseProbe": True,
        "artifactRegistryReuseProbe": True,
        "ocrShardCache": {
            "root": "/tmp/ocr-shards",
            "fileCount": 2,
            "totalBytes": 7,
            "maxBytes": 100,
        },
        "summary": summary,
        "results": [result],
        "distinctMiss": distinct_report,
        "structureBaseline": {"enabled": True, "fixtureCount": 1, "totalErrorRows": 0},
    }


def _distinct_artifact_report() -> dict[str, object]:
    return {
        "resourceTypeCounts": {"document": 1, "table": 1},
        "resourceStatusCounts": {"ok": 2},
        "structureBlockTypeCounts": {"document": 1, "table": 1},
        "metricsStatusCounts": {"succeeded": 2},
        "documentTimingStatusCounts": {"ok": 3},
        "documentTimingPhaseElapsedMs": {"doclingConvert": 20.0, "total": 30.0},
        "imageAttachmentAudit": {
            "format": "png",
            "widthPx": 640,
            "heightPx": 480,
            "pixelCount": 307200,
            "dimensionSource": "png_ihdr",
            "rustAccelerationCandidate": "image_ocr_cache_candidate",
        },
        "archiveAttachmentAudit": {
            "archiveFormat": "tar.gz",
            "memberCount": 10,
            "regularFileCount": 10,
            "xmlMemberCount": 1,
            "imageMemberCount": 3,
            "totalMemberSizeBytes": 267702,
            "extensionCounts": {"html": 3, "tif": 3, "txt": 3, "xml": 1},
            "largestMemberSizeBytes": 59518,
            "rustAccelerationCandidate": "mets_gbs_member_manifest_candidate",
        },
    }
