//! Event topic constants for type-safe routing.

/// Agent-related topic group.
pub mod agent;
mod catalog;
/// File-related topic group.
pub mod file;
/// Omega workflow topic group.
pub mod omega;

pub use catalog::{
    AGENT_ACTION, AGENT_RESULT, AGENT_THINK, ALL_TOPICS, CORTEX_INDEX_UPDATED, CORTEX_QUERY,
    FILE_CHANGED, FILE_CREATED, FILE_DELETED, FILE_RENAMED, OMEGA_BRANCH_CREATED,
    OMEGA_BRANCH_ISOLATE, OMEGA_BRANCH_MERGED, OMEGA_BRANCH_ROLLBACK, OMEGA_CONFLICT_DETECTED,
    OMEGA_CONFLICT_RESOLVED, OMEGA_EXPERIENCE_LOAD, OMEGA_EXPERIENCE_LOADED,
    OMEGA_MISSION_COMPLETE, OMEGA_MISSION_FAIL, OMEGA_MISSION_START, OMEGA_RECOVERY_SUCCESS,
    OMEGA_RECOVERY_TRIGGER, OMEGA_SEMANTIC_COMPLETE, OMEGA_SEMANTIC_SCAN, OMEGA_SKILL_CRYSTALLIZE,
    OMEGA_SKILL_CRYSTALLIZED, OMEGA_TASK_COMPLETE, OMEGA_TASK_DECOMPOSE, OMEGA_TASK_DECOMPOSED,
    OMEGA_TASK_FAIL, OMEGA_TASK_START, SYSTEM_READY, SYSTEM_SHUTDOWN, TOOL_REQUEST, TOOL_RESPONSE,
    TUI_EVENT,
};
