//! Omega workflow topic grouping.

use super::{
    OMEGA_MISSION_COMPLETE, OMEGA_MISSION_FAIL, OMEGA_MISSION_START, OMEGA_TASK_COMPLETE,
    OMEGA_TASK_FAIL, OMEGA_TASK_START,
};

/// Core omega execution topics.
pub const OMEGA_TOPICS: &[(&str, &str)] = &[
    ("MISSION_START", OMEGA_MISSION_START),
    ("MISSION_COMPLETE", OMEGA_MISSION_COMPLETE),
    ("MISSION_FAIL", OMEGA_MISSION_FAIL),
    ("TASK_START", OMEGA_TASK_START),
    ("TASK_COMPLETE", OMEGA_TASK_COMPLETE),
    ("TASK_FAIL", OMEGA_TASK_FAIL),
];
