use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ControlCliCommand {
    Activity {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        json: bool,
    },
    ActivityQueue {
        ledger_path: PathBuf,
        run_id: String,
        task_queue: Option<String>,
        json: bool,
    },
    ActivityComplete {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        completed_at_ms: u64,
        output_hash: Option<String>,
        metadata: Option<String>,
        json: bool,
    },
    ActivityFail {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        failed_at_ms: u64,
        error_code: String,
        message: String,
        retryable: bool,
        attempt: u32,
        metadata: Option<String>,
        json: bool,
    },
    ActivityStart {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        worker_id: String,
        started_at_ms: u64,
        attempt: u32,
        json: bool,
    },
    ApplyRecoveryPlan {
        ledger_path: PathBuf,
        valkey_url: String,
        namespace: Option<String>,
        run_id: String,
        now_ms: u64,
        attempt: u32,
        reason: String,
        max_attempts: u32,
        backoff_ms: u64,
        require_human_approval: bool,
        priority: i64,
        json: bool,
    },
    Decision {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        decision_id: String,
        json: bool,
    },
    History {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
    Heartbeat {
        ledger_path: PathBuf,
        run_id: String,
        worker_id: String,
        observed_at_ms: u64,
        expires_at_ms: u64,
        metadata: Option<String>,
        json: bool,
    },
    Lease {
        ledger_path: PathBuf,
        run_id: String,
        step_id: String,
        json: bool,
    },
    HotState {
        valkey_url: String,
        namespace: Option<String>,
        now_ms: u64,
        json: bool,
    },
    QueryState {
        ledger_path: PathBuf,
        run_id: String,
        now_ms: u64,
        json: bool,
    },
    RecoverySnapshot {
        ledger_path: PathBuf,
        run_id: String,
        now_ms: u64,
        json: bool,
    },
    Signal {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        signal_name: String,
        payload: String,
        received_at_ms: u64,
        json: bool,
    },
    View {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
    Step {
        ledger_path: PathBuf,
        run_id: String,
        step_id: String,
        json: bool,
    },
    Timer {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        timer_id: String,
        json: bool,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ControlCliOutput {
    pub(crate) rendered: String,
}
