use std::path::PathBuf;

use super::activity_args::ActivitySettleOutcomeArg;
use super::activity_executor::ActivityExecutorKindArg;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ControlCliCommand {
    ActivityAdmitPlan {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        occurred_at_ms: u64,
        schedule_plan_json_path: PathBuf,
        json: bool,
    },
    Activity {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        json: bool,
    },
    ActivityQueue {
        ledger_path: PathBuf,
        run_id: String,
        task_queue: Option<String>,
        json: bool,
    },
    ActivityClaim {
        valkey_url: String,
        namespace: Option<String>,
        worker_id: String,
        task_queue: Option<String>,
        now_ms: u64,
        lease_ttl_ms: u64,
        json: bool,
    },
    ActivityMirror {
        ledger_path: PathBuf,
        valkey_url: String,
        namespace: Option<String>,
        run_id: String,
        task_queue: Option<String>,
        priority: i64,
        not_before_ms: u64,
        metadata: Option<String>,
        json: bool,
    },
    ActivityRelease {
        valkey_url: String,
        namespace: Option<String>,
        lease_json: String,
        json: bool,
    },
    ActivityReclaim {
        valkey_url: String,
        namespace: Option<String>,
        lease_json: String,
        now_ms: u64,
        json: bool,
    },
    ActivityScheduleLlm {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        occurred_at_ms: u64,
        llm_activity_json: String,
        json: bool,
    },
    ActivityComplete {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        completed_at_ms: u64,
        output_hash: Option<String>,
        metadata: Option<String>,
        json: bool,
    },
    ActivityCompleteWorkerTask {
        ledger_path: PathBuf,
        worker_task_json: String,
        completed_at_ms: u64,
        output_hash: Option<String>,
        metadata: Option<String>,
        json: bool,
    },
    ActivityFail {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        failed_at_ms: u64,
        error_code: String,
        message: String,
        retryable: bool,
        attempt: u32,
        metadata: Option<String>,
        json: bool,
    },
    ActivityFailWorkerTask {
        ledger_path: PathBuf,
        worker_task_json: String,
        failed_at_ms: u64,
        error_code: String,
        message: String,
        retryable: bool,
        metadata: Option<String>,
        json: bool,
    },
    ActivityStart {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        activity_id: String,
        worker_id: String,
        started_at_ms: u64,
        attempt: u32,
        json: bool,
    },
    ActivityStartWorkerTask {
        ledger_path: PathBuf,
        worker_task_json: String,
        worker_id: String,
        started_at_ms: u64,
        json: bool,
    },
    ActivitySettle {
        ledger_path: PathBuf,
        valkey_url: String,
        namespace: Option<String>,
        leased_task_json: String,
        outcome: ActivitySettleOutcomeArg,
        settled_at_ms: u64,
        output_hash: Option<String>,
        error_code: Option<String>,
        message: Option<String>,
        retryable: Option<bool>,
        metadata: Option<String>,
        json: bool,
    },
    ActivityTake {
        ledger_path: PathBuf,
        valkey_url: String,
        namespace: Option<String>,
        worker_id: String,
        task_queue: Option<String>,
        now_ms: u64,
        lease_ttl_ms: u64,
        json: bool,
    },
    ActivityWorkerOnce {
        ledger_path: PathBuf,
        valkey_url: String,
        namespace: Option<String>,
        worker_id: String,
        task_queue: Option<String>,
        now_ms: u64,
        lease_ttl_ms: u64,
        executor: ActivityExecutorKindArg,
        outcome: ActivitySettleOutcomeArg,
        settled_at_ms: u64,
        output_ref_json: Option<String>,
        output_hash: Option<String>,
        output_artifact_path: Option<PathBuf>,
        output_artifact_content: Option<String>,
        output_artifact_id: Option<String>,
        output_artifact_kind: Option<String>,
        openai_compatible_base_url: Option<String>,
        openai_compatible_api_key: Option<String>,
        openai_compatible_timeout_ms: Option<u64>,
        error_code: Option<String>,
        message: Option<String>,
        retryable: Option<bool>,
        metadata: Option<String>,
        json: bool,
    },
    ActivityWorkerLoop {
        ledger_path: PathBuf,
        valkey_url: String,
        namespace: Option<String>,
        worker_id: String,
        task_queue: Option<String>,
        now_ms: u64,
        now_step_ms: u64,
        lease_ttl_ms: u64,
        heartbeat_ttl_ms: Option<u64>,
        poll_limit: u32,
        empty_limit: u32,
        executor: ActivityExecutorKindArg,
        outcome: ActivitySettleOutcomeArg,
        settled_at_ms: u64,
        settled_step_ms: u64,
        output_hash: Option<String>,
        output_artifact_dir: Option<PathBuf>,
        output_artifact_kind: Option<String>,
        openai_compatible_base_url: Option<String>,
        openai_compatible_api_key: Option<String>,
        openai_compatible_timeout_ms: Option<u64>,
        error_code: Option<String>,
        message: Option<String>,
        retryable: Option<bool>,
        metadata: Option<String>,
        json: bool,
    },
    ApplyRecoveryPlan {
        ledger_path: PathBuf,
        valkey_url: String,
        namespace: Option<String>,
        run_id: String,
        now_ms: u64,
        attempt: u32,
        reason: String,
        max_attempts: u32,
        backoff_ms: u64,
        require_human_approval: bool,
        priority: i64,
        json: bool,
    },
    RunCreate {
        ledger_path: PathBuf,
        run_id: String,
        occurred_at_ms: u64,
        intent: String,
        json: bool,
    },
    Costs {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
    Decision {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        decision_id: String,
        json: bool,
    },
    History {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
    Heartbeat {
        ledger_path: PathBuf,
        valkey_url: Option<String>,
        namespace: Option<String>,
        run_id: String,
        worker_id: String,
        observed_at_ms: u64,
        expires_at_ms: u64,
        metadata: Option<String>,
        json: bool,
    },
    Lease {
        ledger_path: PathBuf,
        run_id: String,
        step_id: String,
        json: bool,
    },
    Leases {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
    LlmActivities {
        ledger_path: PathBuf,
        run_id: String,
        require_request_audit: bool,
        json: bool,
    },
    HotState {
        valkey_url: String,
        namespace: Option<String>,
        now_ms: u64,
        json: bool,
    },
    QueryState {
        ledger_path: PathBuf,
        run_id: String,
        now_ms: u64,
        json: bool,
    },
    RecoverySnapshot {
        ledger_path: PathBuf,
        run_id: String,
        now_ms: u64,
        json: bool,
    },
    Summary {
        ledger_path: PathBuf,
        run_id: String,
        now_ms: u64,
        json: bool,
    },
    Signal {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        signal_name: String,
        payload: String,
        received_at_ms: u64,
        json: bool,
    },
    Signals {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
    View {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
    Step {
        ledger_path: PathBuf,
        run_id: String,
        step_id: String,
        json: bool,
    },
    Timer {
        ledger_path: PathBuf,
        run_id: String,
        step_id: Option<String>,
        timer_id: String,
        json: bool,
    },
    Timers {
        ledger_path: PathBuf,
        run_id: String,
        json: bool,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ControlCliOutput {
    pub(crate) rendered: String,
}
