//! Stable Wendao Flight query-contract boundary and public re-exports.

mod analysis;
mod graph;
mod identifiers;
mod metadata;
mod query;
mod repo;
mod rerank;
mod search;
#[cfg(test)]
#[path = "../../../tests/unit/transport/query_contract/mod.rs"]
mod tests;
mod vfs;

pub use analysis::{
    ANALYSIS_CODE_AST_ROUTE, ANALYSIS_DOCUMENT_EXTRACT_ROUTE,
    ANALYSIS_DOCUMENT_EXTRACT_STATUS_ROUTE, ANALYSIS_MARKDOWN_ROUTE, ANALYSIS_PDF_OCR_SHARDS_ROUTE,
    DOCUMENT_EXTRACT_FAST_TEXT_PROFILE, DOCUMENT_EXTRACT_FULL_PROFILE,
    DocumentExtractFlightRequest, DocumentExtractMode, WENDAO_ANALYSIS_LINE_HEADER,
    WENDAO_ANALYSIS_PATH_HEADER, WENDAO_ANALYSIS_REPO_HEADER,
    WENDAO_DOCUMENT_EXTRACT_ERROR_ROW_HEADER, WENDAO_DOCUMENT_EXTRACT_FORCE_HEADER,
    WENDAO_DOCUMENT_EXTRACT_JOB_ID_HEADER, WENDAO_DOCUMENT_EXTRACT_MODE_HEADER,
    WENDAO_DOCUMENT_EXTRACT_OUTPUT_DIR_HEADER, WENDAO_DOCUMENT_EXTRACT_PROFILE_HEADER,
    WENDAO_DOCUMENT_EXTRACT_SOURCE_PATH_HEADER, WENDAO_DOCUMENT_EXTRACT_WAIT_MS_HEADER,
    WENDAO_PDF_OCR_WORKERS_HEADER, normalize_document_extract_profile,
    validate_code_ast_analysis_request, validate_document_extract_request,
    validate_markdown_analysis_request,
};
pub use graph::{
    GRAPH_NEIGHBORS_DEFAULT_HOPS, GRAPH_NEIGHBORS_DEFAULT_LIMIT, GRAPH_NEIGHBORS_ROUTE,
    TOPOLOGY_3D_ROUTE, WENDAO_GRAPH_DIRECTION_HEADER, WENDAO_GRAPH_HOPS_HEADER,
    WENDAO_GRAPH_LIMIT_HEADER, WENDAO_GRAPH_NODE_ID_HEADER, validate_graph_neighbors_request,
};
pub use identifiers::{EntityIdRef, ModuleIdRef, NodeIdRef, PageIdRef, RepoIdRef, RequestIdRef};
pub use metadata::{WENDAO_SCHEMA_VERSION_HEADER, flight_descriptor_path, normalize_flight_route};
#[cfg(feature = "transport")]
pub use query::validate_sql_query_request;
pub use query::{QUERY_SQL_ROUTE, WENDAO_SQL_QUERY_HEADER};
pub use repo::{
    ANALYSIS_REFINE_DOC_ROUTE, ANALYSIS_REPO_DOC_COVERAGE_ROUTE, ANALYSIS_REPO_INDEX_ROUTE,
    ANALYSIS_REPO_INDEX_STATUS_ROUTE, ANALYSIS_REPO_OVERVIEW_ROUTE,
    ANALYSIS_REPO_PROJECTED_PAGE_INDEX_TREE_ROUTE, ANALYSIS_REPO_SYNC_ROUTE,
    WENDAO_REFINE_DOC_ENTITY_ID_HEADER, WENDAO_REFINE_DOC_REPO_HEADER,
    WENDAO_REFINE_DOC_USER_HINTS_HEADER, WENDAO_REPO_DOC_COVERAGE_MODULE_HEADER,
    WENDAO_REPO_DOC_COVERAGE_REPO_HEADER, WENDAO_REPO_INDEX_REFRESH_HEADER,
    WENDAO_REPO_INDEX_REPO_HEADER, WENDAO_REPO_INDEX_REQUEST_ID_HEADER,
    WENDAO_REPO_INDEX_STATUS_REPO_HEADER, WENDAO_REPO_OVERVIEW_REPO_HEADER,
    WENDAO_REPO_PROJECTED_PAGE_INDEX_TREE_PAGE_ID_HEADER,
    WENDAO_REPO_PROJECTED_PAGE_INDEX_TREE_REPO_HEADER, WENDAO_REPO_SYNC_MODE_HEADER,
    WENDAO_REPO_SYNC_REPO_HEADER, validate_refine_doc_request, validate_repo_doc_coverage_request,
    validate_repo_index_request, validate_repo_index_status_request,
    validate_repo_overview_request, validate_repo_projected_page_index_tree_request,
    validate_repo_sync_request,
};
#[cfg(feature = "transport")]
pub use rerank::{
    RERANK_REQUEST_DOC_ID_COLUMN, RERANK_REQUEST_EMBEDDING_COLUMN,
    RERANK_REQUEST_QUERY_EMBEDDING_COLUMN, RERANK_REQUEST_VECTOR_SCORE_COLUMN,
    RERANK_RESPONSE_DOC_ID_COLUMN, RERANK_RESPONSE_FINAL_SCORE_COLUMN, RERANK_RESPONSE_RANK_COLUMN,
    RERANK_RESPONSE_SEMANTIC_SCORE_COLUMN, RERANK_RESPONSE_VECTOR_SCORE_COLUMN,
    RerankScoredCandidate, WENDAO_RERANK_MIN_FINAL_SCORE_HEADER, WENDAO_RERANK_TOP_K_HEADER,
    score_rerank_request_batch, score_rerank_request_batch_with_weights,
    validate_rerank_request_batch, validate_rerank_request_schema, validate_rerank_response_batch,
    validate_rerank_response_schema,
};
pub use rerank::{RERANK_ROUTE, RerankScoreWeights, WENDAO_RERANK_DIMENSION_HEADER};
pub use search::{
    REPO_SEARCH_BEST_SECTION_COLUMN, REPO_SEARCH_DEFAULT_LIMIT, REPO_SEARCH_DOC_ID_COLUMN,
    REPO_SEARCH_HIERARCHY_COLUMN, REPO_SEARCH_LANGUAGE_COLUMN, REPO_SEARCH_MATCH_REASON_COLUMN,
    REPO_SEARCH_NAVIGATION_CATEGORY_COLUMN, REPO_SEARCH_NAVIGATION_LINE_COLUMN,
    REPO_SEARCH_NAVIGATION_LINE_END_COLUMN, REPO_SEARCH_NAVIGATION_PATH_COLUMN,
    REPO_SEARCH_PATH_COLUMN, REPO_SEARCH_ROUTE, REPO_SEARCH_SCORE_COLUMN, REPO_SEARCH_TAGS_COLUMN,
    REPO_SEARCH_TITLE_COLUMN, SEARCH_AST_ROUTE, SEARCH_ATTACHMENTS_ROUTE,
    SEARCH_AUTOCOMPLETE_ROUTE, SEARCH_DEFINITION_ROUTE, SEARCH_INTENT_ROUTE,
    SEARCH_KNOWLEDGE_ROUTE, SEARCH_REFERENCES_ROUTE, SEARCH_SYMBOLS_ROUTE,
    WENDAO_ATTACHMENT_SEARCH_CASE_SENSITIVE_HEADER, WENDAO_ATTACHMENT_SEARCH_EXT_FILTERS_HEADER,
    WENDAO_ATTACHMENT_SEARCH_KIND_FILTERS_HEADER, WENDAO_AUTOCOMPLETE_LIMIT_HEADER,
    WENDAO_AUTOCOMPLETE_PREFIX_HEADER, WENDAO_DEFINITION_LINE_HEADER,
    WENDAO_DEFINITION_PATH_HEADER, WENDAO_DEFINITION_QUERY_HEADER,
    WENDAO_REPO_SEARCH_FILENAME_FILTERS_HEADER, WENDAO_REPO_SEARCH_LANGUAGE_FILTERS_HEADER,
    WENDAO_REPO_SEARCH_LIMIT_HEADER, WENDAO_REPO_SEARCH_PATH_PREFIXES_HEADER,
    WENDAO_REPO_SEARCH_QUERY_HEADER, WENDAO_REPO_SEARCH_REPO_HEADER,
    WENDAO_REPO_SEARCH_TAG_FILTERS_HEADER, WENDAO_REPO_SEARCH_TITLE_FILTERS_HEADER,
    WENDAO_SEARCH_INTENT_HEADER, WENDAO_SEARCH_LIMIT_HEADER, WENDAO_SEARCH_QUERY_HEADER,
    WENDAO_SEARCH_REPO_HEADER, validate_attachment_search_request, validate_autocomplete_request,
    validate_definition_request, validate_repo_search_request,
};
pub use vfs::{
    VFS_CONTENT_ROUTE, VFS_RESOLVE_ROUTE, VFS_SCAN_ROUTE, WENDAO_VFS_PATH_HEADER,
    validate_vfs_content_request, validate_vfs_resolve_request,
};
