use super::{ConstructCard, ConstructLintMapping};
use crate::construct_cards::ConstructStatus;

pub(super) const fn card(lint_mappings: &'static [ConstructLintMapping]) -> ConstructCard {
    ConstructCard {
        id: "user-task.interaction",
        title: "Structured User Interaction Task",
        domain: "bpmn",
        status: ConstructStatus::Draft,
        summary: "Ask the user a bounded question and map the answer to declared outputs.",
        purpose: "Use when a workflow checkpoint needs human approval, selection, or free-form input.",
        requires: &[
            "userTask with qianji config",
            "interaction type is one of input, confirm, choice, or choice_input",
            "outputs declared for downstream routing",
            "dynamic questions are generated by an upstream serviceTask and referenced with qianji:question ref",
        ],
        allows: &[
            "input",
            "confirm",
            "choice",
            "choice_input",
            "free-form answer text through input or choice_input",
            "<qianji:question ref=\"currentQuestion\"/> when currentQuestion is declared in qianji:inputs",
        ],
        forbids: &[
            "hardcoded downstream prompt behavior outside the card contract",
            "asking a userTask prompt to generate a question; userTask does not run an agent",
            "unsupported interaction type values such as free_form",
            "choices whose values do not match downstream output mapping",
            "gateway conditions over undeclared answers",
        ],
        example: r#"<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:qianji="https://qianji.dev/bpmn/extensions"
  targetNamespace="https://qianji.dev/examples">
  <process id="Process_UserInteraction" isExecutable="true">
    <startEvent id="Start"/>
    <sequenceFlow id="Flow_Start_Approve" sourceRef="Start" targetRef="Task_Approve"/>
    <userTask id="Task_Approve" name="Approve design">
      <extensionElements>
        <qianji:config>
          <qianji:prompt>Review the proposed design.</qianji:prompt>
          <qianji:outputs>approved,feedback</qianji:outputs>
          <qianji:interaction type="choice_input">
            <qianji:question>Does this design look right?</qianji:question>
            <qianji:choice value="approved" label="Approve">Continue.</qianji:choice>
            <qianji:choice value="changes" label="Request changes">Revise first.</qianji:choice>
            <qianji:freeText name="feedback" optional="true"/>
          </qianji:interaction>
        </qianji:config>
      </extensionElements>
    </userTask>
    <sequenceFlow id="Flow_Approve_End" sourceRef="Task_Approve" targetRef="End"/>
    <endEvent id="End"/>
  </process>
</definitions>"#,
        lint_mappings,
        next_cards: &["gateway.exclusive.bounded"],
    }
}
