use super::{ConstructCard, ConstructLintMapping};
use crate::construct_cards::ConstructStatus;

pub(super) const fn card(lint_mappings: &'static [ConstructLintMapping]) -> ConstructCard {
    ConstructCard {
        id: "user-task.interaction",
        title: "Structured User Interaction Task",
        domain: "bpmn",
        status: ConstructStatus::Draft,
        summary: "Ask the user for approval, selection, missing context, or escalation and map the answer to declared outputs.",
        purpose: "Use when a workflow checkpoint needs human approval, selection, free-form input, answers to subagent questions, missing context, or escalation handling.",
        requires: &[
            "userTask or manualTask with native BPMN IO metadata",
            "interaction type is one of input, confirm, choice, or choice_input",
            "documentation or question data input provides the user-facing question",
            "ioSpecification declares dataInput name=\"interactionType\" and dataOutput name=\"answer\"",
            "dataOutputAssociation maps answer to exactly one workflow variable",
            "choice and choice_input declare either one static choices JSON assignment or one choices sourceRef",
            "dynamic questions are generated by an upstream serviceTask and referenced with a question data input sourceRef",
            "dynamic multiple-choice options are generated by an upstream serviceTask and referenced with a choices data input sourceRef",
            "dynamic currentChoices items include a non-empty value field; value is the string returned by the userTask",
            "looping interactions also use loop.interactive.progress",
        ],
        allows: &[
            "input",
            "confirm",
            "choice",
            "choice_input",
            "free-form answer text through input or choice_input",
            "static choices through a JSON array literal on dataInput name=\"choices\"",
            "question sourceRef currentQuestion when the task consumes a generated question variable",
            "choices sourceRef currentChoices when the task consumes generated choice objects",
            "currentChoices JSON array objects with required value and optional label/description fields",
            "pure free-form input through interactionType input and optional freeText JSON metadata",
        ],
        forbids: &[
            "hardcoded downstream prompt behavior outside the card contract",
            "asking a userTask prompt to generate a question; userTask does not run an agent",
            "unsupported interaction type values such as free_form",
            "empty option lists for choice or choice_input",
            "numbered option prose embedded inside currentQuestion when a choices sourceRef is available",
            "literal variable names such as currentQuestion rendered as the user-facing question",
            "choices whose values do not match downstream output mapping",
            "multiple answer outputs on a userTask interaction; derive secondary variables in a following serviceTask",
            "gateway conditions over undeclared answers",
        ],
        example: r#"<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  targetNamespace="https://example.test/bpmn">
  <process id="Process_UserInteraction" isExecutable="true">
    <startEvent id="Start"/>
    <sequenceFlow id="Flow_Start_Prepare" sourceRef="Start" targetRef="Task_PrepareQuestion"/>
    <serviceTask id="Task_PrepareQuestion" name="Prepare question" implementation="${environment.services.runAgent}">
      <documentation>Write one concise question and prepare 2-4 choices. Do not embed option text in currentQuestion.</documentation>
      <ioSpecification>
        <dataInput id="Task_PrepareQuestion_Input_context" name="context"/>
        <dataOutput id="Task_PrepareQuestion_Output_currentQuestion" name="currentQuestion"/>
        <dataOutput id="Task_PrepareQuestion_Output_currentChoices" name="currentChoices"/>
        <inputSet><dataInputRefs>Task_PrepareQuestion_Input_context</dataInputRefs></inputSet>
        <outputSet>
          <dataOutputRefs>Task_PrepareQuestion_Output_currentQuestion</dataOutputRefs>
          <dataOutputRefs>Task_PrepareQuestion_Output_currentChoices</dataOutputRefs>
        </outputSet>
      </ioSpecification>
      <dataInputAssociation><sourceRef>context</sourceRef><targetRef>Task_PrepareQuestion_Input_context</targetRef></dataInputAssociation>
      <dataOutputAssociation><sourceRef>Task_PrepareQuestion_Output_currentQuestion</sourceRef><targetRef>currentQuestion</targetRef></dataOutputAssociation>
      <dataOutputAssociation><sourceRef>Task_PrepareQuestion_Output_currentChoices</sourceRef><targetRef>currentChoices</targetRef></dataOutputAssociation>
    </serviceTask>
    <sequenceFlow id="Flow_Prepare_Answer" sourceRef="Task_PrepareQuestion" targetRef="Task_Answer"/>
    <userTask id="Task_Answer" name="Answer question">
      <documentation>Ask the generated question.</documentation>
      <ioSpecification>
        <dataInput id="Task_Answer_Input_interactionType" name="interactionType"/>
        <dataInput id="Task_Answer_Input_question" name="question"/>
        <dataInput id="Task_Answer_Input_choices" name="choices"/>
        <dataInput id="Task_Answer_Input_freeText" name="freeText"/>
        <dataOutput id="Task_Answer_Output_answer" name="answer"/>
        <inputSet>
          <dataInputRefs>Task_Answer_Input_interactionType</dataInputRefs>
          <dataInputRefs>Task_Answer_Input_question</dataInputRefs>
          <dataInputRefs>Task_Answer_Input_choices</dataInputRefs>
          <dataInputRefs>Task_Answer_Input_freeText</dataInputRefs>
        </inputSet>
        <outputSet><dataOutputRefs>Task_Answer_Output_answer</dataOutputRefs></outputSet>
      </ioSpecification>
      <dataInputAssociation><targetRef>Task_Answer_Input_interactionType</targetRef><assignment><from>choice_input</from><to>Task_Answer_Input_interactionType</to></assignment></dataInputAssociation>
      <dataInputAssociation><sourceRef>currentQuestion</sourceRef><targetRef>Task_Answer_Input_question</targetRef></dataInputAssociation>
      <dataInputAssociation><sourceRef>currentChoices</sourceRef><targetRef>Task_Answer_Input_choices</targetRef></dataInputAssociation>
      <dataInputAssociation><targetRef>Task_Answer_Input_freeText</targetRef><assignment><from>{"name":"optionalDetail","optional":true}</from><to>Task_Answer_Input_freeText</to></assignment></dataInputAssociation>
      <dataOutputAssociation><sourceRef>Task_Answer_Output_answer</sourceRef><targetRef>userAnswer</targetRef></dataOutputAssociation>
    </userTask>
    <sequenceFlow id="Flow_Answer_End" sourceRef="Task_Answer" targetRef="End"/>
    <endEvent id="End"/>
  </process>
</definitions>"#,
        lint_mappings,
        next_cards: &["loop.interactive.progress", "gateway.exclusive.bounded"],
    }
}
