use super::{ConstructCard, ConstructLintMapping};
use crate::construct_cards::ConstructStatus;

pub(super) const fn card(lint_mappings: &'static [ConstructLintMapping]) -> ConstructCard {
    ConstructCard {
        id: "user-task.interaction",
        title: "Structured User Interaction Task",
        domain: "bpmn",
        status: ConstructStatus::Draft,
        summary: "Ask the user for approval, selection, missing context, or escalation and map the answer to declared outputs.",
        purpose: "Use when a workflow checkpoint needs human approval, selection, free-form input, answers to subagent questions, missing context, or escalation handling.",
        requires: &[
            "userTask with qianji config",
            "interaction type is one of input, confirm, choice, or choice_input",
            "qianji:tools is present and empty for userTask nodes",
            "qianji:inputs is present, even when empty",
            "qianji:outputs declares exactly the qianji:result output for userTask interactions",
            "choice and choice_input declare either static qianji:choice entries or one qianji:choices ref",
            "qianji:result maps the semantic answer to the single declared qianji:outputs name",
            "dynamic questions are generated by an upstream serviceTask and referenced with qianji:question ref",
            "dynamic multiple-choice options are generated by an upstream serviceTask and referenced with qianji:choices ref",
            "dynamic currentChoices items include a non-empty value field; value is the string returned by the userTask",
            "looping interactions also use loop.interactive.progress",
        ],
        allows: &[
            "input",
            "confirm",
            "choice",
            "choice_input",
            "free-form answer text through input or choice_input",
            "static choices through qianji:choice value plus optional label and body description",
            "<qianji:question ref=\"currentQuestion\"/> when currentQuestion is declared in qianji:inputs",
            "<qianji:choices ref=\"currentChoices\"/> when currentChoices is declared in qianji:inputs",
            "currentChoices has qianji:outputSchema kind=\"choice_array\" with required value and optional label/description fields",
            "pure free-form input through qianji:interaction type=\"input\" with qianji:freeText",
        ],
        forbids: &[
            "hardcoded downstream prompt behavior outside the card contract",
            "asking a userTask prompt to generate a question; userTask does not run an agent",
            "unsupported interaction type values such as free_form",
            "empty option lists for choice or choice_input",
            "numbered option prose embedded inside currentQuestion when qianji:choices ref is available",
            "literal variable names such as currentQuestion rendered as the user-facing question",
            "choices whose values do not match downstream output mapping",
            "multiple qianji:outputs on a userTask interaction; derive secondary variables in a following serviceTask",
            "gateway conditions over undeclared answers",
        ],
        example: r#"<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:qianji="https://qianji.dev/bpmn/extensions"
  targetNamespace="https://qianji.dev/examples">
  <process id="Process_UserInteraction" isExecutable="true">
    <startEvent id="Start"/>
    <sequenceFlow id="Flow_Start_Prepare" sourceRef="Start" targetRef="Task_PrepareQuestion"/>
    <serviceTask id="Task_PrepareQuestion" name="Prepare question" implementation="${environment.services.runAgent}">
      <extensionElements>
        <qianji:config>
          <qianji:prompt>Write one concise question and prepare 2-4 choices. Do not embed option text in currentQuestion.</qianji:prompt>
          <qianji:tools></qianji:tools>
          <qianji:inputs>context</qianji:inputs>
          <qianji:outputs>currentQuestion,currentChoices</qianji:outputs>
          <qianji:outputSchema name="currentChoices" kind="choice_array" value="required" label="optional" description="optional"/>
        </qianji:config>
      </extensionElements>
    </serviceTask>
    <sequenceFlow id="Flow_Prepare_Answer" sourceRef="Task_PrepareQuestion" targetRef="Task_Answer"/>
    <userTask id="Task_Answer" name="Answer question">
      <extensionElements>
        <qianji:config>
          <qianji:prompt>Ask the generated question.</qianji:prompt>
          <qianji:tools></qianji:tools>
          <qianji:inputs>currentQuestion,currentChoices</qianji:inputs>
          <qianji:outputs>userAnswer</qianji:outputs>
          <qianji:interaction type="choice_input">
            <qianji:question ref="currentQuestion"/>
            <qianji:choices ref="currentChoices"/>
            <qianji:freeText name="optionalDetail" optional="true"/>
            <qianji:result output="userAnswer"/>
          </qianji:interaction>
        </qianji:config>
      </extensionElements>
    </userTask>
    <sequenceFlow id="Flow_Answer_End" sourceRef="Task_Answer" targetRef="End"/>
    <endEvent id="End"/>
  </process>
</definitions>"#,
        lint_mappings,
        next_cards: &["loop.interactive.progress", "gateway.exclusive.bounded"],
    }
}
