use super::{ConstructCard, ConstructLintMapping};
use crate::construct_cards::ConstructStatus;

pub(super) const fn card(lint_mappings: &'static [ConstructLintMapping]) -> ConstructCard {
    ConstructCard {
        id: "loop.interactive.progress",
        title: "Interactive Loop Progress Contract",
        domain: "bpmn",
        status: ConstructStatus::Draft,
        summary: "Revisit a userTask only when the loop updates declared progress inputs such as the next question, choices, attempt, or remaining count.",
        purpose: "Use when an interactive workflow may ask multiple clarifying questions, request iterative review, or loop back to the same userTask after processing the previous answer.",
        requires: &[
            "a serviceTask generates the next question, choices, and route/progress variables",
            "currentChoices is emitted as JSON array objects with required non-empty value and optional label/description",
            "the serviceTask qianji:inputs include the prior userTask answer when the loop repeats",
            "the serviceTask qianji:outputs include every variable used by the loop gateway",
            "the repeated userTask declares qianji:inputs for the resolved question and choices",
            "each loop iteration changes at least one declared userTask input before returning to that userTask",
            "the gateway has one unconditional default exit branch",
        ],
        allows: &[
            "same userTask id reused across iterations",
            "currentQuestion/currentChoices regenerated by an upstream serviceTask",
            "questionsRemaining or attempt counters as explicit progress state",
            "userAnswer fed into the next-question serviceTask inputs",
            "route conditions over declared booleans or numeric comparisons",
        ],
        forbids: &[
            "returning to the same userTask with the same resolved question and choices",
            "placing option prose inside currentQuestion instead of currentChoices",
            "routing back to a userTask when the prior userAnswer is not an input to the next-question serviceTask",
            "gateway route variables that are not emitted by an in-loop qianji task",
            "using a conditional expression on the gateway default branch",
        ],
        example: r#"<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:qianji="https://qianji.dev/bpmn/extensions"
  targetNamespace="https://qianji.dev/examples">
  <process id="Process_InteractiveLoop" isExecutable="true">
    <startEvent id="Start"/>
    <sequenceFlow id="Flow_Start_Prepare" sourceRef="Start" targetRef="Task_PrepareNextQuestion"/>
    <serviceTask id="Task_PrepareNextQuestion" name="Prepare next question" implementation="${environment.services.runAgent}">
      <extensionElements>
        <qianji:config>
          <qianji:prompt>Use context and prior userAnswer to decide whether another question is needed. If needed, output changed currentQuestion and currentChoices values. Always output questionsRemaining as a JSON number.</qianji:prompt>
          <qianji:tools></qianji:tools>
          <qianji:inputs>context,userAnswer,attempt</qianji:inputs>
          <qianji:outputs>currentQuestion,currentChoices,questionsRemaining,attempt</qianji:outputs>
          <qianji:outputSchema name="currentChoices" kind="choice_array" value="required" label="optional" description="optional"/>
        </qianji:config>
      </extensionElements>
    </serviceTask>
    <sequenceFlow id="Flow_Prepare_Gateway" sourceRef="Task_PrepareNextQuestion" targetRef="Gateway_MoreQuestions"/>
    <exclusiveGateway id="Gateway_MoreQuestions" default="Flow_NoMoreQuestions"/>
    <sequenceFlow id="Flow_MoreQuestions" sourceRef="Gateway_MoreQuestions" targetRef="Task_AnswerQuestion">
      <conditionExpression xsi:type="tFormalExpression">questionsRemaining &gt; 0</conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="Flow_NoMoreQuestions" sourceRef="Gateway_MoreQuestions" targetRef="End"/>
    <userTask id="Task_AnswerQuestion" name="Answer question">
      <extensionElements>
        <qianji:config>
          <qianji:prompt>Ask the generated question.</qianji:prompt>
          <qianji:tools></qianji:tools>
          <qianji:inputs>currentQuestion,currentChoices</qianji:inputs>
          <qianji:outputs>userAnswer</qianji:outputs>
          <qianji:interaction type="choice_input">
            <qianji:question ref="currentQuestion"/>
            <qianji:choices ref="currentChoices"/>
            <qianji:result output="userAnswer"/>
          </qianji:interaction>
        </qianji:config>
      </extensionElements>
    </userTask>
    <sequenceFlow id="Flow_Answer_Prepare" sourceRef="Task_AnswerQuestion" targetRef="Task_PrepareNextQuestion"/>
    <endEvent id="End"/>
  </process>
</definitions>"#,
        lint_mappings,
        next_cards: &["user-task.interaction", "gateway.exclusive.bounded"],
    }
}
