//! Modelica AST-query Arrow contract facade.

mod analysis;
mod batch;
mod rows;
mod schema;
mod values;

pub(crate) use analysis::decode_modelica_ast_query_analysis;
pub(crate) use batch::build_modelica_ast_query_request_batch;
pub(crate) use rows::decode_modelica_ast_query_response_rows;
pub(crate) use schema::{
    MODELICA_AST_QUERY_ATTRIBUTE_CONTAINS_COLUMN, MODELICA_AST_QUERY_ATTRIBUTE_EQUALS_COLUMN,
    MODELICA_AST_QUERY_ATTRIBUTE_KEY_COLUMN, MODELICA_AST_QUERY_BACKEND_COLUMN,
    MODELICA_AST_QUERY_ERROR_MESSAGE_COLUMN, MODELICA_AST_QUERY_LIMIT_COLUMN,
    MODELICA_AST_QUERY_MATCH_ARRAY_DIMENSIONS_COLUMN, MODELICA_AST_QUERY_MATCH_CLASS_PATH_COLUMN,
    MODELICA_AST_QUERY_MATCH_COMPONENT_KIND_COLUMN, MODELICA_AST_QUERY_MATCH_COUNT_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEFAULT_VALUE_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEPENDENCY_ALIAS_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEPENDENCY_FORM_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEPENDENCY_KIND_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEPENDENCY_LOCAL_NAME_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEPENDENCY_MEMBER_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEPENDENCY_PARENT_COLUMN,
    MODELICA_AST_QUERY_MATCH_DEPENDENCY_TARGET_COLUMN, MODELICA_AST_QUERY_MATCH_DIRECTION_COLUMN,
    MODELICA_AST_QUERY_MATCH_INDEX_COLUMN, MODELICA_AST_QUERY_MATCH_IS_ENCAPSULATED_COLUMN,
    MODELICA_AST_QUERY_MATCH_IS_FINAL_COLUMN, MODELICA_AST_QUERY_MATCH_IS_PARTIAL_COLUMN,
    MODELICA_AST_QUERY_MATCH_LINE_END_COLUMN, MODELICA_AST_QUERY_MATCH_LINE_START_COLUMN,
    MODELICA_AST_QUERY_MATCH_MODIFIER_NAMES_COLUMN, MODELICA_AST_QUERY_MATCH_NAME_COLUMN,
    MODELICA_AST_QUERY_MATCH_NODE_KIND_COLUMN, MODELICA_AST_QUERY_MATCH_OWNER_NAME_COLUMN,
    MODELICA_AST_QUERY_MATCH_OWNER_PATH_COLUMN, MODELICA_AST_QUERY_MATCH_PATH_COLUMN,
    MODELICA_AST_QUERY_MATCH_SIGNATURE_COLUMN, MODELICA_AST_QUERY_MATCH_START_VALUE_COLUMN,
    MODELICA_AST_QUERY_MATCH_TEXT_COLUMN, MODELICA_AST_QUERY_MATCH_TOP_LEVEL_COLUMN,
    MODELICA_AST_QUERY_MATCH_TYPE_NAME_COLUMN, MODELICA_AST_QUERY_MATCH_UNIT_COLUMN,
    MODELICA_AST_QUERY_MATCH_VARIABILITY_COLUMN, MODELICA_AST_QUERY_MATCH_VISIBILITY_COLUMN,
    MODELICA_AST_QUERY_NAME_CONTAINS_COLUMN, MODELICA_AST_QUERY_NAME_EQUALS_COLUMN,
    MODELICA_AST_QUERY_NODE_KIND_COLUMN, MODELICA_AST_QUERY_PRIMARY_NAME_COLUMN,
    MODELICA_AST_QUERY_REQUEST_ID_COLUMN, MODELICA_AST_QUERY_SIGNATURE_CONTAINS_COLUMN,
    MODELICA_AST_QUERY_SOURCE_ID_COLUMN, MODELICA_AST_QUERY_SOURCE_TEXT_COLUMN,
    MODELICA_AST_QUERY_SUCCESS_COLUMN, MODELICA_AST_QUERY_SUMMARY_KIND_COLUMN,
    MODELICA_AST_QUERY_TEXT_CONTAINS_COLUMN, ModelicaAstQueryRequest, ModelicaAstQueryResponseRow,
};

#[cfg(test)]
#[path = "../../../../tests/unit/modelica_plugin/ast_query_contract.rs"]
mod tests;
