//! Backend-neutral read-through helpers for generated artifact bytes.

use crate::artifact_cache::{
    ArtifactBlobCache, ArtifactBlobWrite, ArtifactBlobWriteOutcome, ArtifactCacheError, ArtifactKey,
};

/// Result of an artifact read-through operation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArtifactReadThrough {
    bytes: Vec<u8>,
    cache_hit: bool,
    write: Option<ArtifactBlobWriteOutcome>,
}

impl ArtifactReadThrough {
    /// Create a cache-hit outcome from cached bytes.
    #[must_use]
    pub fn hit(bytes: Vec<u8>) -> Self {
        Self {
            bytes,
            cache_hit: true,
            write: None,
        }
    }

    /// Create a cache-miss outcome from newly generated bytes.
    #[must_use]
    pub fn miss(bytes: Vec<u8>, write: ArtifactBlobWriteOutcome) -> Self {
        Self {
            bytes,
            cache_hit: false,
            write: Some(write),
        }
    }

    /// Borrow the artifact bytes.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        self.bytes.as_slice()
    }

    /// Consume this outcome and return the artifact bytes.
    #[must_use]
    pub fn into_bytes(self) -> Vec<u8> {
        self.bytes
    }

    /// Number of artifact bytes returned to the caller.
    #[must_use]
    pub fn byte_len(&self) -> usize {
        self.bytes.len()
    }

    /// Whether the bytes came from an existing cached artifact.
    #[must_use]
    pub const fn cache_hit(&self) -> bool {
        self.cache_hit
    }

    /// Whether the operation had to build and write new artifact bytes.
    #[must_use]
    pub const fn cache_miss(&self) -> bool {
        !self.cache_hit
    }

    /// Write outcome when this operation populated the cache.
    #[must_use]
    pub const fn write_outcome(&self) -> Option<ArtifactBlobWriteOutcome> {
        self.write
    }
}

/// Read cached artifact bytes or build and persist them on a miss.
///
/// # Errors
///
/// Returns [`ArtifactCacheError`] when the cache read/write fails or when the
/// builder fails to produce artifact bytes.
pub fn read_through_artifact_bytes(
    cache: &dyn ArtifactBlobCache,
    key: &ArtifactKey,
    build: impl FnOnce() -> Result<Vec<u8>, ArtifactCacheError>,
) -> Result<ArtifactReadThrough, ArtifactCacheError> {
    if let Some(read) = cache.read(key)? {
        return Ok(ArtifactReadThrough::hit(read.into_bytes()));
    }
    let bytes = build()?;
    let write = cache.write(key, ArtifactBlobWrite::new(bytes.as_slice()))?;
    Ok(ArtifactReadThrough::miss(bytes, write))
}
