//! Backend-neutral read-through helpers for generated artifact bytes.

use std::time::{Duration, Instant};

use crate::artifact_cache::{
    ArtifactBlobCache, ArtifactBlobFetch, ArtifactBlobFetchStatus, ArtifactBlobReadStatus,
    ArtifactBlobWrite, ArtifactBlobWriteOutcome, ArtifactBytes, ArtifactCacheError, ArtifactKey,
};

/// Read-through source status for generated artifact bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArtifactReadThroughStatus {
    /// Bytes came from the cache backend.
    Hit,
    /// Bytes were generated after a normal cache miss.
    Miss,
    /// Bytes were generated while the cache backend reported pressure.
    Throttled,
}

impl ArtifactReadThroughStatus {
    /// Return whether this status came from existing cached bytes.
    #[must_use]
    pub const fn is_hit(self) -> bool {
        matches!(self, Self::Hit)
    }

    /// Return whether this status had to generate bytes.
    #[must_use]
    pub const fn is_miss(self) -> bool {
        !self.is_hit()
    }

    /// Return whether the miss path was caused by backend pressure.
    #[must_use]
    pub const fn is_throttled(self) -> bool {
        matches!(self, Self::Throttled)
    }
}

/// Result of an artifact read-through operation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArtifactReadThrough {
    bytes: ArtifactBytes,
    key: Option<ArtifactKey>,
    backend_name: &'static str,
    status: ArtifactReadThroughStatus,
    write: Option<ArtifactBlobWriteOutcome>,
    read_elapsed: Duration,
    build_elapsed: Duration,
    write_elapsed: Duration,
}

impl ArtifactReadThrough {
    /// Create a cache-hit outcome from cached bytes.
    #[must_use]
    pub fn hit(bytes: Vec<u8>) -> Self {
        Self::hit_shared(ArtifactBytes::from_vec(bytes))
    }

    /// Create a cache-hit outcome from shared cached bytes.
    #[must_use]
    pub fn hit_shared(bytes: ArtifactBytes) -> Self {
        Self {
            bytes,
            key: None,
            backend_name: "artifact-cache",
            status: ArtifactReadThroughStatus::Hit,
            write: None,
            read_elapsed: Duration::ZERO,
            build_elapsed: Duration::ZERO,
            write_elapsed: Duration::ZERO,
        }
    }

    /// Create a cache-miss outcome from newly generated bytes.
    #[must_use]
    pub fn miss(bytes: Vec<u8>, write: ArtifactBlobWriteOutcome) -> Self {
        Self::miss_shared(ArtifactBytes::from_vec(bytes), write)
    }

    /// Create a cache-miss outcome from shared newly generated bytes.
    #[must_use]
    pub fn miss_shared(bytes: ArtifactBytes, write: ArtifactBlobWriteOutcome) -> Self {
        Self {
            bytes,
            key: None,
            backend_name: "artifact-cache",
            status: ArtifactReadThroughStatus::Miss,
            write: Some(write),
            read_elapsed: Duration::ZERO,
            build_elapsed: Duration::ZERO,
            write_elapsed: Duration::ZERO,
        }
    }

    /// Borrow the artifact bytes.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        self.bytes.as_slice()
    }

    /// Consume this outcome and return the artifact bytes.
    #[must_use]
    pub fn into_bytes(self) -> Vec<u8> {
        self.bytes.to_vec()
    }

    /// Consume this outcome and return shared artifact bytes.
    #[must_use]
    pub fn into_shared_bytes(self) -> ArtifactBytes {
        self.bytes
    }

    /// Number of artifact bytes returned to the caller.
    #[must_use]
    pub fn byte_len(&self) -> usize {
        self.bytes.len()
    }

    /// Whether the bytes came from an existing cached artifact.
    #[must_use]
    pub const fn cache_hit(&self) -> bool {
        self.status.is_hit()
    }

    /// Whether the operation had to build and write new artifact bytes.
    #[must_use]
    pub const fn cache_miss(&self) -> bool {
        self.status.is_miss()
    }

    /// Whether cache pressure forced a build path without treating the result
    /// as a normal writable miss.
    #[must_use]
    pub const fn cache_throttled(&self) -> bool {
        self.status.is_throttled()
    }

    /// Stable cache backend name used for this operation.
    #[must_use]
    pub const fn backend_name(&self) -> &'static str {
        self.backend_name
    }

    /// Artifact key used by the read-through call when available.
    #[must_use]
    pub const fn artifact_key(&self) -> Option<&ArtifactKey> {
        self.key.as_ref()
    }

    /// Read-through status.
    #[must_use]
    pub const fn status(&self) -> ArtifactReadThroughStatus {
        self.status
    }

    /// Write outcome when this operation populated the cache.
    #[must_use]
    pub const fn write_outcome(&self) -> Option<ArtifactBlobWriteOutcome> {
        self.write
    }

    /// Elapsed time spent reading from the cache backend.
    #[must_use]
    pub const fn read_elapsed(&self) -> Duration {
        self.read_elapsed
    }

    /// Elapsed time spent building artifact bytes after a miss.
    #[must_use]
    pub const fn build_elapsed(&self) -> Duration {
        self.build_elapsed
    }

    /// Elapsed time spent writing artifact bytes after a normal miss.
    #[must_use]
    pub const fn write_elapsed(&self) -> Duration {
        self.write_elapsed
    }

    fn cache_hit_receipt(
        key: &ArtifactKey,
        backend_name: &'static str,
        bytes: ArtifactBytes,
        read_elapsed: Duration,
    ) -> Self {
        Self {
            bytes,
            key: Some(key.clone()),
            backend_name,
            status: ArtifactReadThroughStatus::Hit,
            write: None,
            read_elapsed,
            build_elapsed: Duration::ZERO,
            write_elapsed: Duration::ZERO,
        }
    }

    fn built_receipt(
        key: &ArtifactKey,
        backend_name: &'static str,
        bytes: ArtifactBytes,
        status: ArtifactReadThroughStatus,
        write: Option<ArtifactBlobWriteOutcome>,
        timings: ArtifactReadThroughTimings,
    ) -> Self {
        Self {
            bytes,
            key: Some(key.clone()),
            backend_name,
            status,
            write,
            read_elapsed: timings.read,
            build_elapsed: timings.build,
            write_elapsed: timings.write,
        }
    }

    fn from_blob_fetch(
        key: &ArtifactKey,
        backend_name: &'static str,
        fetched: ArtifactBlobFetch,
    ) -> Self {
        let status = match fetched.status() {
            ArtifactBlobFetchStatus::Hit => ArtifactReadThroughStatus::Hit,
            ArtifactBlobFetchStatus::Miss => ArtifactReadThroughStatus::Miss,
            ArtifactBlobFetchStatus::Throttled => ArtifactReadThroughStatus::Throttled,
        };
        let timings = ArtifactReadThroughTimings {
            read: fetched.read_elapsed(),
            build: fetched.build_elapsed(),
            write: fetched.write_elapsed(),
        };
        let write = fetched.write_outcome();
        let bytes = fetched.into_shared_bytes();
        Self::built_receipt(key, backend_name, bytes, status, write, timings)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ArtifactReadThroughTimings {
    read: Duration,
    build: Duration,
    write: Duration,
}

/// Read cached artifact bytes or build and persist them on a miss.
///
/// # Errors
///
/// Returns [`ArtifactCacheError`] when the cache read/write fails or when the
/// builder fails to produce artifact bytes.
pub fn read_through_artifact_bytes(
    cache: &dyn ArtifactBlobCache,
    key: &ArtifactKey,
    build: impl FnOnce() -> Result<Vec<u8>, ArtifactCacheError>,
) -> Result<ArtifactReadThrough, ArtifactCacheError> {
    let read_started = Instant::now();
    let read_status = cache.read_with_status(key)?;
    let read_elapsed = read_started.elapsed();
    if let ArtifactBlobReadStatus::Hit(read) = read_status {
        return Ok(ArtifactReadThrough::cache_hit_receipt(
            key,
            cache.backend_name(),
            read.into_shared_bytes(),
            read_elapsed,
        ));
    }

    let status = if read_status.is_throttled() {
        ArtifactReadThroughStatus::Throttled
    } else {
        ArtifactReadThroughStatus::Miss
    };

    let build_started = Instant::now();
    let bytes = build()?;
    let build_elapsed = build_started.elapsed();

    let write_started = Instant::now();
    let write = if status.is_throttled() {
        None
    } else {
        Some(cache.write(key, ArtifactBlobWrite::new(bytes.as_slice()))?)
    };
    let write_elapsed = write_started.elapsed();

    Ok(ArtifactReadThrough::built_receipt(
        key,
        cache.backend_name(),
        ArtifactBytes::from_vec(bytes),
        status,
        write,
        ArtifactReadThroughTimings {
            read: read_elapsed,
            build: build_elapsed,
            write: write_elapsed,
        },
    ))
}

/// Fetch cached artifact bytes or build and persist them through the backend.
///
/// Backends with native fetch-through support may coalesce concurrent same-key
/// misses. Use this helper when the builder can be moved into a backend-owned
/// execution path. Use [`read_through_artifact_bytes`] when the builder must
/// borrow local state.
///
/// # Errors
///
/// Returns [`ArtifactCacheError`] when the cache read/write fails or when the
/// builder fails to produce artifact bytes.
pub fn fetch_through_artifact_bytes(
    cache: &dyn ArtifactBlobCache,
    key: &ArtifactKey,
    build: impl FnOnce() -> Result<Vec<u8>, ArtifactCacheError> + Send + 'static,
) -> Result<ArtifactReadThrough, ArtifactCacheError> {
    let fetched = cache.fetch_through(key, Box::new(build))?;
    Ok(ArtifactReadThrough::from_blob_fetch(
        key,
        cache.backend_name(),
        fetched,
    ))
}
