#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common.sh"
PROJECT_ROOT="$(process_project_root "$SCRIPT_DIR" "../../../..")"
PROJECT_DATA_ROOT="$(process_data_root "$PROJECT_ROOT")"
PROJECT_RUNTIME_ROOT="$(process_runtime_root "$PROJECT_ROOT")"

export WENDAO_CODE_PARSER_PACKAGE_DIR="${WENDAO_CODE_PARSER_PACKAGE_DIR:-$PROJECT_DATA_ROOT/WendaoCodeParser.jl}"
export WENDAO_CODE_PARSER_JULIA_PROJECT="${WENDAO_CODE_PARSER_JULIA_PROJECT:-$WENDAO_CODE_PARSER_PACKAGE_DIR}"
export WENDAO_CODE_PARSER_CONFIG="${WENDAO_CODE_PARSER_CONFIG:-$WENDAO_CODE_PARSER_PACKAGE_DIR/config/live/parser_summary.toml}"
export WENDAO_CODE_PARSER_SCRIPT="${WENDAO_CODE_PARSER_SCRIPT:-$WENDAO_CODE_PARSER_PACKAGE_DIR/scripts/run_service.jl}"
export WENDAOCODEPARSER_CONFIG="${WENDAOCODEPARSER_CONFIG:-$WENDAO_CODE_PARSER_CONFIG}"

export WENDAOSEARCH_SERVICE_NAME="${WENDAOSEARCH_SERVICE_NAME:-wendaocodeparser-parser-summary}"
export WENDAOSEARCH_RUNTIME_DIR="${WENDAOSEARCH_RUNTIME_DIR:-$PROJECT_RUNTIME_ROOT/wendaocodeparser}"
export WENDAOSEARCH_PACKAGE_DIR="${WENDAOSEARCH_PACKAGE_DIR:-$WENDAO_CODE_PARSER_PACKAGE_DIR}"
export WENDAOSEARCH_JULIA_PROJECT="${WENDAOSEARCH_JULIA_PROJECT:-$WENDAO_CODE_PARSER_JULIA_PROJECT}"
export WENDAOSEARCH_CONFIG="${WENDAOSEARCH_CONFIG:-$WENDAO_CODE_PARSER_CONFIG}"
export WENDAOSEARCH_SCRIPT="${WENDAOSEARCH_SCRIPT:-$WENDAO_CODE_PARSER_SCRIPT}"
export WENDAOSEARCH_PACKAGE_REPO_URL="${WENDAOSEARCH_PACKAGE_REPO_URL:-https://github.com/tao3k/WendaoCodeParser.jl.git}"
export WENDAOSEARCH_PACKAGE_LABEL="${WENDAOSEARCH_PACKAGE_LABEL:-WendaoCodeParser.jl checkout}"
export WENDAO_SEARCH_USE_ACTIVE_PROJECT="${WENDAO_SEARCH_USE_ACTIVE_PROJECT:-1}"

exec bash "$PROJECT_ROOT/scripts/runtime/processes/wendaosearch/entrypoint.sh"
