//! Analysis-route query contracts for Wendao Flight metadata.

mod code_ast;
mod document_extract;
mod headers;
mod markdown;

pub use code_ast::{ANALYSIS_CODE_AST_ROUTE, validate_code_ast_analysis_request};
pub use document_extract::{
    ANALYSIS_AUDIO_SHARDS_ROUTE, ANALYSIS_DOCUMENT_EXTRACT_ROUTE,
    ANALYSIS_DOCUMENT_EXTRACT_STATUS_ROUTE, ANALYSIS_PDF_OCR_SHARDS_ROUTE,
    DOCUMENT_EXTRACT_FAST_TEXT_PROFILE, DOCUMENT_EXTRACT_FULL_PROFILE,
    DocumentExtractFlightRequest, DocumentExtractMode, WENDAO_AUDIO_HOSTED_BASE_URL_HEADER,
    WENDAO_AUDIO_HOSTED_MODEL_HEADER, WENDAO_AUDIO_HOSTED_PROVIDER_HEADER,
    WENDAO_AUDIO_WORKER_HEADER, WENDAO_AUDIO_WORKERS_HEADER,
    WENDAO_DOCUMENT_EXTRACT_ERROR_ROW_HEADER, WENDAO_DOCUMENT_EXTRACT_FORCE_HEADER,
    WENDAO_DOCUMENT_EXTRACT_JOB_ID_HEADER, WENDAO_DOCUMENT_EXTRACT_MODE_HEADER,
    WENDAO_DOCUMENT_EXTRACT_OUTPUT_DIR_HEADER, WENDAO_DOCUMENT_EXTRACT_PAGE_RANGE_HEADER,
    WENDAO_DOCUMENT_EXTRACT_PROFILE_HEADER, WENDAO_DOCUMENT_EXTRACT_SOURCE_PATH_HEADER,
    WENDAO_DOCUMENT_EXTRACT_SOURCE_PATH_UTF8_HEX_HEADER, WENDAO_DOCUMENT_EXTRACT_WAIT_MS_HEADER,
    WENDAO_PDF_OCR_WORKERS_HEADER, decode_document_extract_source_path_utf8_hex,
    encode_document_extract_source_path_utf8_hex, normalize_document_extract_profile,
    validate_document_extract_request,
};
pub use headers::{
    WENDAO_ANALYSIS_LINE_HEADER, WENDAO_ANALYSIS_PATH_HEADER, WENDAO_ANALYSIS_REPO_HEADER,
};
pub use markdown::{ANALYSIS_MARKDOWN_ROUTE, validate_markdown_analysis_request};
