//! Julia episodic-recall transport columns and row types.

mod contract;
mod schema;

pub use contract::{
    build_memory_julia_episodic_recall_request_batch,
    decode_memory_julia_episodic_recall_score_rows, memory_julia_episodic_recall_request_schema,
    memory_julia_episodic_recall_response_schema,
    validate_memory_julia_episodic_recall_request_batch,
    validate_memory_julia_episodic_recall_request_batches,
    validate_memory_julia_episodic_recall_request_schema,
    validate_memory_julia_episodic_recall_response_batch,
    validate_memory_julia_episodic_recall_response_batches,
    validate_memory_julia_episodic_recall_response_schema,
};
pub use schema::{
    MEMORY_JULIA_EPISODIC_RECALL_CANDIDATE_ID_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_CONFIDENCE_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_CREATED_AT_MS_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_FAILURE_COUNT_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_FINAL_SCORE_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_INTENT_EMBEDDING_COLUMN, MEMORY_JULIA_EPISODIC_RECALL_K1_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_K2_COLUMN, MEMORY_JULIA_EPISODIC_RECALL_LAMBDA_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_MIN_SCORE_COLUMN, MEMORY_JULIA_EPISODIC_RECALL_Q_VALUE_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_QUERY_EMBEDDING_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_QUERY_ID_COLUMN, MEMORY_JULIA_EPISODIC_RECALL_QUERY_TEXT_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_RANKING_REASON_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_REQUEST_COLUMNS, MEMORY_JULIA_EPISODIC_RECALL_RESPONSE_COLUMNS,
    MEMORY_JULIA_EPISODIC_RECALL_RETRIEVAL_COUNT_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_RETRIEVAL_MODE_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_SCENARIO_PACK_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_SCHEMA_VERSION_COLUMN, MEMORY_JULIA_EPISODIC_RECALL_SCOPE_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_SEMANTIC_SCORE_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_SUCCESS_COUNT_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_UPDATED_AT_MS_COLUMN,
    MEMORY_JULIA_EPISODIC_RECALL_UTILITY_SCORE_COLUMN, MemoryJuliaEpisodicRecallRequestRow,
    MemoryJuliaEpisodicRecallScoreRow,
};
