"""Arrow contracts for audio shard workers."""

from __future__ import annotations

from .audio_shard_contracts import (
    AUDIO_SHARD_DEFAULT_PROFILE,
    AUDIO_SHARD_DEFAULT_TASK_PROFILE,
    AUDIO_SHARD_INPUT_SCHEMA,
    AUDIO_SHARD_INPUT_SCHEMA_VERSION,
    AUDIO_SHARD_RESULT_SCHEMA,
    AUDIO_SHARD_RESULT_SCHEMA_VERSION,
    AudioShardWorkerProtocol,
)
from .audio_shard_results import (
    failed_audio_shard_result,
    normalize_audio_shard_result,
    skipped_audio_shard_result,
    succeeded_audio_shard_result,
)
from .audio_shard_tables import (
    AUDIO_SHARD_MAX_WORKERS_ENV,
    AUDIO_SHARD_WORKERS_ENV,
    build_audio_shard_result_table,
    resolve_audio_shard_worker_count,
    validate_audio_shard_input_table,
)
from .audio_shard_workers import (
    AUDIO_BACKEND_DOCLING_PROFILE,
    AUDIO_BACKEND_HOSTED_PROFILE,
    AUDIO_HOSTED_API_KEY_ENV,
    AUDIO_HOSTED_BASE_URL_ENV,
    AUDIO_HOSTED_MAX_ATTEMPTS_ENV,
    AUDIO_HOSTED_MODEL_ENV,
    AUDIO_HOSTED_OPENROUTER_PROVIDER,
    AUDIO_HOSTED_PROVIDER_ENV,
    AUDIO_HOSTED_REQUEST_CONCURRENCY_ENV,
    AUDIO_HOSTED_TIMEOUT_SECONDS_ENV,
    AUDIO_WORKER_ENV,
    DoclingAudioShardWorker,
    HostedAudioConfig,
    HostedAudioShardWorker,
    SkippingAudioShardWorker,
    UnsupportedAudioShardWorker,
    build_audio_shard_worker,
    hosted_audio_config_from_env,
    hosted_audio_payload,
    normalize_audio_worker_name,
)

__all__ = [
    "AUDIO_BACKEND_DOCLING_PROFILE",
    "AUDIO_BACKEND_HOSTED_PROFILE",
    "AUDIO_HOSTED_API_KEY_ENV",
    "AUDIO_HOSTED_BASE_URL_ENV",
    "AUDIO_HOSTED_MAX_ATTEMPTS_ENV",
    "AUDIO_HOSTED_MODEL_ENV",
    "AUDIO_HOSTED_OPENROUTER_PROVIDER",
    "AUDIO_HOSTED_PROVIDER_ENV",
    "AUDIO_HOSTED_REQUEST_CONCURRENCY_ENV",
    "AUDIO_HOSTED_TIMEOUT_SECONDS_ENV",
    "AUDIO_SHARD_DEFAULT_PROFILE",
    "AUDIO_SHARD_DEFAULT_TASK_PROFILE",
    "AUDIO_SHARD_INPUT_SCHEMA",
    "AUDIO_SHARD_INPUT_SCHEMA_VERSION",
    "AUDIO_SHARD_MAX_WORKERS_ENV",
    "AUDIO_SHARD_RESULT_SCHEMA",
    "AUDIO_SHARD_RESULT_SCHEMA_VERSION",
    "AUDIO_SHARD_WORKERS_ENV",
    "AUDIO_WORKER_ENV",
    "AudioShardWorkerProtocol",
    "DoclingAudioShardWorker",
    "HostedAudioConfig",
    "HostedAudioShardWorker",
    "SkippingAudioShardWorker",
    "UnsupportedAudioShardWorker",
    "build_audio_shard_result_table",
    "build_audio_shard_worker",
    "failed_audio_shard_result",
    "hosted_audio_config_from_env",
    "hosted_audio_payload",
    "normalize_audio_shard_result",
    "normalize_audio_worker_name",
    "resolve_audio_shard_worker_count",
    "skipped_audio_shard_result",
    "succeeded_audio_shard_result",
    "validate_audio_shard_input_table",
]
