from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[6]


def test_python_agent_legacy_scripts_are_absent() -> None:
    removed = [
        "scripts/benchmark_kernel.py",
        "scripts/benchmark_knowledge_recall.py",
        "scripts/benchmark_skills_tools.py",
        "scripts/benchmark_skills_tools_gate.sh",
        "scripts/benchmark_skills_tools_ci.sh",
        "scripts/benchmark_json_vs_arrow.py",
        "scripts/benchmark_wendao_search.sh",
        "scripts/benchmark_wendao_related.sh",
        "scripts/bootcamp_adversarial_v2.py",
        "scripts/ci-local-recall-gates.sh",
        "scripts/compare_cli_runner_summary.py",
        "scripts/knowledge_recall_perf_gate.py",
        "scripts/recall_profile.py",
        "scripts/render_skills_tools_ci_summary.py",
        "scripts/render_embedding_role_perf_summary.py",
        "scripts/evaluate_wendao_retrieval.sh",
        "scripts/skills_monitor.py",
        "scripts/sovereign-wip.sh",
        "scripts/sync-for-gpt.sh",
        "scripts/test_upstream_cli_memory.sh",
        "scripts/visual_stress_test.py",
        "scripts/verify_rust_pruner.py",
        "scripts/verify_recall.py",
        "scripts/verify_generator.py",
        "scripts/test_render.py",
        "scripts/verify_archiver.py",
        "scripts/recall_profile_phases.py",
        "scripts/runtime/test_ocr_chain.sh",
        "scripts/bootcamp_distributed_swarm.py",
        "scripts/bootcamp_distributed_swarm_gate.py",
        "scripts/bootcamp_epic_forge_cluster.py",
        "scripts/bootcamp_forge_trigger.py",
        "scripts/bootcamp_run_forge.py",
        "scripts/bootcamp_swarm_evolution.py",
        "scripts/bootcamp_verify_evolution.py",
        "scripts/compare_memory_usage.py",
        "scripts/run_minimal_load_test.py",
        "scripts/simulate_signal_rain.py",
        "scripts/test_minimax_endpoints.py",
        "scripts/test_real.py",
        "scripts/test_repo_analyzer_e2e.py",
        "scripts/test_smart_commit_e2e.py",
        "scripts/test_bootcamp_distributed_swarm.py",
        "scripts/test_bootcamp_distributed_swarm_gate.py",
        "scripts/test_bootcamp_adversarial_v2.py",
        "scripts/verify_memrl_scenarios.legacy.py",
        "scripts/test_render_embedding_role_perf_summary.py",
        "scripts/recall_paper_to_file.py",
        "scripts/benchmark_rust_core.py",
        "scripts/generate_keyword_backend_multi_model_report.py",
        "scripts/generate_vector_search_options_contract.py",
        "scripts/probe_llm_models.py",
        "scripts/generate_llm_index.py",
        "scripts/llm_fingerprint_audit.py",
        "scripts/run_keyword_backend_multi_model_batches.py",
        "scripts/tests/benchmarks/__init__.py",
        "scripts/tests/benchmarks/_knowledge_snapshot.py",
        "scripts/tests/benchmarks/test_knowledge_snapshot.py",
        "scripts/tests/test_llm_fingerprint_audit.py",
        "scripts/verify_brain.py",
        "scripts/verify_pipeline.py",
        "scripts/verify_skill_descriptions.py",
        "scripts/verify_grand_integration.py",
        "packages/python/foundation/tests/unit/services/test_keyword_multi_model_batches.py",
        "scripts/test_generate_vector_search_options_contract.py",
    ]

    for relative_path in removed:
        assert not (PROJECT_ROOT / relative_path).exists(), relative_path
