//! ast-grep patterns for different languages.
//!
//! Centralized pattern definitions for symbol extraction.
//!
//! Generated by `xiuxian_macros::patterns!` macro.

/// Python class pattern: `class $NAME`
pub const PYTHON_CLASS: &str = "class $NAME";
/// Python function pattern: `def $NAME`
pub const PYTHON_DEF: &str = "def $NAME";
/// Python async function pattern: `async def $NAME`
pub const PYTHON_ASYNC_DEF: &str = "async def $NAME";

/// Rust struct pattern: `pub struct $NAME`
pub const RUST_STRUCT: &str = "pub struct $NAME";
/// Rust function pattern: `pub fn $NAME`
pub const RUST_FN: &str = "pub fn $NAME";
/// Rust enum pattern: `enum $NAME`
pub const RUST_ENUM: &str = "enum $NAME";
/// Rust trait pattern: `trait $NAME`
pub const RUST_TRAIT: &str = "trait $NAME";
/// Rust impl pattern: `impl $NAME`
pub const RUST_IMPL: &str = "impl $NAME";

/// JavaScript class pattern: `class $NAME`
pub const JS_CLASS: &str = "class $NAME";
/// JavaScript function pattern: `function $NAME`
pub const JS_FN: &str = "function $NAME";

/// TypeScript interface pattern: `interface $NAME`
pub const TS_INTERFACE: &str = "interface $NAME";

/// Go patterns
/// Go struct pattern: `type $NAME struct`
pub const GO_STRUCT: &str = "type $NAME struct";
/// Go function pattern: `func $NAME`
pub const GO_FN: &str = "func $NAME";

/// Java patterns
/// Java class pattern: `class $NAME`
pub const JAVA_CLASS: &str = "class $NAME";
/// Java method pattern: `$NAME(`
pub const JAVA_METHOD: &str = "$NAME(";

/// All patterns as a const array for iteration
pub const ALL_PATTERNS: &[(&str, &str)] = &[
    ("PYTHON_CLASS", PYTHON_CLASS),
    ("PYTHON_DEF", PYTHON_DEF),
    ("PYTHON_ASYNC_DEF", PYTHON_ASYNC_DEF),
    ("RUST_STRUCT", RUST_STRUCT),
    ("RUST_FN", RUST_FN),
    ("RUST_ENUM", RUST_ENUM),
    ("RUST_TRAIT", RUST_TRAIT),
    ("RUST_IMPL", RUST_IMPL),
    ("JS_CLASS", JS_CLASS),
    ("JS_FN", JS_FN),
    ("TS_INTERFACE", TS_INTERFACE),
    ("GO_STRUCT", GO_STRUCT),
    ("GO_FN", GO_FN),
    ("JAVA_CLASS", JAVA_CLASS),
    ("JAVA_METHOD", JAVA_METHOD),
];
