{
  inputs,
  __inputs__,
  pkgs,
  config,
  lib,
}:
let
  inherit (inputs.omnibus.inputs.flops.inputs.dmerge) prepend append merge;
  initConfigs =
    (inputs.omnibus.units.configs {
      inputs = {
        inputs = {
          nixpkgs = __inputs__.nixpkgs-latest;
          inherit (inputs.omnibus.flake.inputs) git-hooks;
        };
      };
    }).exports.default;

  lefthook = initConfigs.lefthook;

  # Dynamic scope detection for ACTIVE packages
  listDirs =
    path:
    if builtins.pathExists path then
      lib.attrNames (
        lib.filterAttrs (name: type: type == "directory") (builtins.readDir path)
      )
    else
      [ ];

  python-scopes = listDirs ../../packages/python;
  rust-scopes = listDirs ../../packages/rust/crates;

  # Active infrastructure scopes
  infra-scopes = [
    "nix" # Infrastructure: devenv.nix, modules
    "docs" # Documentation
    "cli" # Tooling: justfile, lefthook
    "deps" # Dependency management
    "ci" # GitHub Actions, DevContainer
    "data" # JSONL examples, assets
    "version" # Version bump commits
    "claude" # Claude configuration
    "git-ops" # Git operations tools
    "git-workflow" # Git workflow documentation
    "mcp" # MCP application
    "inference" # AI inference engine
    "router" # Tool routing & intent
    "orchestrator" # Orchestrator module
    "skills" # Skill definitions and scripts
  ];

  # Scopes for NEW commits (Infra + Detected Packages)
  active-scopes = lib.unique (
    infra-scopes
    ++ python-scopes
    ++ rust-scopes
    ++ [
      "rust"
      "core"
      "agent"
      "foundation"
    ]
  );

  # Define generator configurations
  generators = [
    {
      name = "lefthook";
      gen =
        (config.omnibus.ops.mkNixago initConfigs.nixago-lefthook)
          initConfigs.lefthook.nix
          initConfigs.lefthook.shell
          # initConfigs.lefthook.prettier # uses removed nixpkgs.nodePackages
          {
            data = {
              pre-commit.commands = {
                prettier = {
                  exclude = append [
                    ".devcontainer.json" # Generated by nix, don't format
                    "CHANGELOG.md"
                    "packages/rust/crates/xiuxian-skills/resources/skill_metadata.schema.json"
                    # "agent/**"
                  ];
                };
                # Update knowledge XML with repomix
                "update-knowledge-xml" = {
                  glob = "agent/knowledge/**/*.md";
                  run = ''cd agent/knowledge && repomix --config repomix.json --output "$PRJ_ROOT"/.data/project_knowledge.xml '';
                };
                # Add ruff for Python formatting
                "format-python" = {
                  glob = "*.py";
                  exclude = [
                    "assets/skills/_template/**" # Template folder - not real code
                  ];
                  run = "uv run ruff format {staged_files}";
                };
                cog-check = {
                  # Still useful to check if types (feat/fix) are correct since last tag
                  run = "cog check --from-latest-tag";
                };
                format-rust = {
                  glob = "*.rs";
                  run = "rustfmt -- {staged_files}";
                };
                format-nickel = {
                  glob = "*.ncl";
                  run = "nickel format -- {staged_files}";
                };
              };
              commit-msg = lefthook.default.data.commit-msg;
              # Remove unnecessary commands from default pre-commit
              commands = builtins.removeAttrs lefthook.default.data.pre-commit.commands [
                "treefmt" # We use nixfmt instead
                # "hunspell" # Not needed for LLM-generated content
                # "typos" # Not needed for LLM-generated content
              ];
            };
          };
    }
    {
      name = "conform";
      gen =
        (config.omnibus.ops.mkNixago initConfigs.nixago-conform)
          initConfigs.conform.default
          {
            # Strict validation for NEW commits
            data.commit = {
              conventional = {
                scopes = append active-scopes;
              };
            };
          };
    }
    {
      name = "cog";
      gen =
        (config.omnibus.ops.mkNixago initConfigs.nixago-cog) initConfigs.cog.default
          {
            data = {
              # REMOVED scopes: cog will now allow any scope in history
              # This solves the "legacy scopes" maintenance problem forever.
              changelog = {
                path = "CHANGELOG.md";
                template = "remote";
                remote = "github.com";
                repository = "xiuxian-artisan-workshop";
                owner = "tao3k";
                authors = [
                  {
                    username = "gtrunsec";
                    signature = "Guangtao";
                  }
                ];
              };
            };
          };
    }
  ];

  # Generate all hooks using map
  generatedHooks = map (g: g.gen) generators;
in
{
  config = {
    packages = lib.flatten (map (g: g.__passthru.packages) generatedHooks);
    enterShell = lib.concatMapStringsSep "\n" (g: g.shellHook) generatedHooks;
  };
}
