//! Environment keys and probe prefixes for `WendaoGraph` host integration.

pub(crate) const WENDAOGRAPH_PACKAGE_DIR_ENV: &str = "WENDAOGRAPH_PACKAGE_DIR";
pub(crate) const WENDAOGRAPH_JULIA_PROJECT_ENV: &str = "WENDAOGRAPH_JULIA_PROJECT";
pub(crate) const WENDAO_GRAPH_PAGE_INDEX_HOST_FIXTURE_ENV: &str =
    "WENDAO_GRAPH_PAGE_INDEX_HOST_FIXTURE";
pub(crate) const WENDAO_GRAPH_PAGE_INDEX_HOST_PROBE_ACTIONS_ENV: &str =
    "WENDAO_GRAPH_PAGE_INDEX_HOST_PROBE_ACTIONS";
pub(crate) const WENDAO_GRAPH_PAGE_INDEX_HOST_PROBE_WARM_SAMPLES_ENV: &str =
    "WENDAO_GRAPH_PAGE_INDEX_HOST_PROBE_WARM_SAMPLES";
pub(crate) const WENDAO_GRAPH_LINK_GRAPH_HOST_PROBE_WARM_SAMPLES_ENV: &str =
    "WENDAO_GRAPH_LINK_GRAPH_HOST_PROBE_WARM_SAMPLES";
pub(crate) const WENDAO_GRAPH_LINK_GRAPH_SYNTHETIC_NODES_ENV: &str =
    "WENDAO_GRAPH_LINK_GRAPH_SYNTHETIC_NODES";
pub(crate) const WENDAO_GRAPH_LINK_GRAPH_SYNTHETIC_FANOUT_ENV: &str =
    "WENDAO_GRAPH_LINK_GRAPH_SYNTHETIC_FANOUT";
pub(crate) const WENDAO_GRAPH_LINK_GRAPH_SYNTHETIC_SEMANTIC_NEIGHBORS_ENV: &str =
    "WENDAO_GRAPH_LINK_GRAPH_SYNTHETIC_SEMANTIC_NEIGHBORS";
pub(crate) const PAGE_INDEX_HOST_PROBE_PREFIX: &str = "wendaograph_page_index_host_probe";
pub(crate) const LINK_GRAPH_HOST_PROBE_PREFIX: &str = "wendaograph_link_graph_host_probe";
