//! Julia parser-summary Arrow contract facade.

mod batch;
mod columns;
mod schema;
mod summary;
mod values;

pub(crate) use batch::{
    build_julia_parser_summary_request_batch, decode_julia_parser_summary_response_rows,
    validate_julia_parser_summary_request_batches, validate_julia_parser_summary_response_batches,
};
pub(crate) use schema::{
    JULIA_PARSER_SUMMARY_BACKEND_COLUMN, JULIA_PARSER_SUMMARY_ERROR_MESSAGE_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_BINDING_KIND_COLUMN, JULIA_PARSER_SUMMARY_ITEM_CONTENT_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_ALIAS_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_FORM_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_IS_RELATIVE_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_KIND_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_LOCAL_NAME_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_MEMBER_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_PARENT_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_RELATIVE_LEVEL_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_DEPENDENCY_TARGET_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_FUNCTION_HAS_VARARGS_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_FUNCTION_KEYWORD_ARITY_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_FUNCTION_POSITIONAL_ARITY_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_FUNCTION_RETURN_TYPE_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_FUNCTION_WHERE_PARAMS_COLUMN, JULIA_PARSER_SUMMARY_ITEM_GROUP_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_KIND_COLUMN, JULIA_PARSER_SUMMARY_ITEM_LINE_END_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_LINE_START_COLUMN, JULIA_PARSER_SUMMARY_ITEM_MODULE_NAME_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_MODULE_PATH_COLUMN, JULIA_PARSER_SUMMARY_ITEM_NAME_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_OWNER_KIND_COLUMN, JULIA_PARSER_SUMMARY_ITEM_OWNER_NAME_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_OWNER_PATH_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_PARAMETER_DEFAULT_VALUE_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_PARAMETER_IS_DEFAULTED_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_PARAMETER_IS_TYPED_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_PARAMETER_IS_VARARG_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_PARAMETER_KIND_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_PARAMETER_TYPE_NAME_COLUMN, JULIA_PARSER_SUMMARY_ITEM_PATH_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_PRIMITIVE_BITS_COLUMN, JULIA_PARSER_SUMMARY_ITEM_REEXPORTED_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_SIGNATURE_COLUMN, JULIA_PARSER_SUMMARY_ITEM_TARGET_KIND_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_TARGET_LINE_END_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_TARGET_LINE_START_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_TARGET_NAME_COLUMN, JULIA_PARSER_SUMMARY_ITEM_TARGET_PATH_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_TOP_LEVEL_COLUMN, JULIA_PARSER_SUMMARY_ITEM_TYPE_KIND_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_TYPE_PARAMETERS_COLUMN,
    JULIA_PARSER_SUMMARY_ITEM_TYPE_SUPERTYPE_COLUMN, JULIA_PARSER_SUMMARY_KIND_COLUMN,
    JULIA_PARSER_SUMMARY_MODULE_KIND_COLUMN, JULIA_PARSER_SUMMARY_MODULE_NAME_COLUMN,
    JULIA_PARSER_SUMMARY_PRIMARY_NAME_COLUMN, JULIA_PARSER_SUMMARY_REQUEST_ID_COLUMN,
    JULIA_PARSER_SUMMARY_SOURCE_ID_COLUMN, JULIA_PARSER_SUMMARY_SOURCE_TEXT_COLUMN,
    JULIA_PARSER_SUMMARY_SUCCESS_COLUMN, JuliaParserSummaryRequestRow,
    JuliaParserSummaryResponseRow,
};
pub(crate) use summary::{decode_julia_parser_file_summary, decode_julia_parser_root_summary};

#[cfg(test)]
#[path = "../../../../tests/unit/plugin/parser_summary/contract.rs"]
mod tests;
