//! Modelica parser-summary Arrow contract facade.

mod batch;
mod columns;
mod file_summary;
mod schema;
mod values;

pub(crate) use batch::{
    build_modelica_parser_summary_request_batch, decode_modelica_parser_summary_response_rows,
    validate_modelica_parser_summary_request_batches,
    validate_modelica_parser_summary_response_batches,
};
pub(crate) use file_summary::decode_modelica_parser_file_summary;
pub(crate) use schema::{
    MODELICA_PARSER_SUMMARY_BACKEND_COLUMN, MODELICA_PARSER_SUMMARY_CLASS_NAME_COLUMN,
    MODELICA_PARSER_SUMMARY_ERROR_MESSAGE_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_ARRAY_DIMENSIONS_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_CLASS_PATH_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_COMPONENT_KIND_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_DEFAULT_VALUE_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_DEPENDENCY_ALIAS_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_DEPENDENCY_FORM_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_DEPENDENCY_LOCAL_NAME_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_DEPENDENCY_TARGET_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_DIRECTION_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_GROUP_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_IS_ENCAPSULATED_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_IS_FINAL_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_IS_PARTIAL_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_KIND_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_LINE_END_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_LINE_START_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_MODIFIER_NAMES_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_NAME_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_OWNER_NAME_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_OWNER_PATH_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_SIGNATURE_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_START_VALUE_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_TEXT_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_TOP_LEVEL_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_TYPE_NAME_COLUMN, MODELICA_PARSER_SUMMARY_ITEM_UNIT_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_VARIABILITY_COLUMN,
    MODELICA_PARSER_SUMMARY_ITEM_VISIBILITY_COLUMN, MODELICA_PARSER_SUMMARY_KIND_COLUMN,
    MODELICA_PARSER_SUMMARY_PRIMARY_NAME_COLUMN, MODELICA_PARSER_SUMMARY_REQUEST_ID_COLUMN,
    MODELICA_PARSER_SUMMARY_RESTRICTION_COLUMN, MODELICA_PARSER_SUMMARY_SOURCE_ID_COLUMN,
    MODELICA_PARSER_SUMMARY_SOURCE_TEXT_COLUMN, MODELICA_PARSER_SUMMARY_SUCCESS_COLUMN,
    ModelicaParserSummaryRequestRow, ModelicaParserSummaryResponseRow,
};

#[cfg(test)]
#[path = "../../../../tests/unit/modelica_plugin/parser_summary_contract.rs"]
mod tests;
