//! Owns the Studio studio router routes surface.

use std::sync::Arc;

use axum::{
    Router,
    routing::{get, post},
};

use crate::contracts::routes as openapi_paths;
use crate::studio::search;

use super::handlers;
use super::state::GatewayState;

/// Create the Studio API router with all endpoints.
#[allow(clippy::too_many_lines)]
pub fn studio_routes() -> Router<Arc<GatewayState>> {
    Router::new()
        .route(
            openapi_paths::API_VFS_ROOT_AXUM_PATH,
            get(handlers::vfs::root_entries),
        )
        .route(
            openapi_paths::API_VFS_SCAN_AXUM_PATH,
            get(handlers::vfs::scan),
        )
        .route(
            openapi_paths::API_VFS_CAT_AXUM_PATH,
            get(handlers::vfs::cat),
        )
        .route("/api/vfs/raw", get(handlers::vfs::raw))
        .route(
            openapi_paths::API_VFS_ENTRY_AXUM_PATH,
            get(handlers::vfs::entry),
        )
        .route(
            openapi_paths::API_TOPOLOGY_3D_AXUM_PATH,
            get(handlers::graph::topology::topology_3d),
        )
        .route(
            openapi_paths::API_SEARCH_INDEX_STATUS_AXUM_PATH,
            get(search::search_index_status),
        )
        .route(
            openapi_paths::API_DOCS_PROJECTED_GAP_REPORT_AXUM_PATH,
            get(handlers::docs::projection::projected_gap::docs_projected_gap_report),
        )
        .route(
            openapi_paths::API_DOCS_PLANNER_ITEM_AXUM_PATH,
            get(handlers::docs::planner::routes::item::planner_item),
        )
        .route(
            openapi_paths::API_DOCS_PLANNER_SEARCH_AXUM_PATH,
            get(handlers::docs::planner::routes::search::planner_search),
        )
        .route(
            openapi_paths::API_DOCS_PLANNER_QUEUE_AXUM_PATH,
            get(handlers::docs::planner::routes::queue::planner_queue),
        )
        .route(
            openapi_paths::API_DOCS_PLANNER_RANK_AXUM_PATH,
            get(handlers::docs::planner::routes::rank::planner_rank),
        )
        .route(
            openapi_paths::API_DOCS_PLANNER_WORKSET_AXUM_PATH,
            get(handlers::docs::planner::routes::workset::planner_workset),
        )
        .route(
            openapi_paths::API_DOCS_SEARCH_AXUM_PATH,
            get(handlers::docs::projection::search::search),
        )
        .route(
            openapi_paths::API_DOCS_RETRIEVAL_AXUM_PATH,
            get(handlers::docs::projection::retrieval::search::retrieval),
        )
        .route(
            openapi_paths::API_DOCS_RETRIEVAL_CONTEXT_AXUM_PATH,
            get(handlers::docs::projection::retrieval::context::retrieval_context),
        )
        .route(
            openapi_paths::API_DOCS_RETRIEVAL_HIT_AXUM_PATH,
            get(handlers::docs::projection::retrieval::context::retrieval_hit),
        )
        .route(
            openapi_paths::API_DOCS_PAGE_AXUM_PATH,
            get(handlers::docs::projection::page::page),
        )
        .route(
            openapi_paths::API_DOCS_PAGE_INDEX_TREE_AXUM_PATH,
            get(handlers::docs::projection::page_index_tree::page_index_tree),
        )
        .route(
            openapi_paths::API_DOCS_FAMILY_CONTEXT_AXUM_PATH,
            get(handlers::docs::projection::family::context::family_context),
        )
        .route(
            openapi_paths::API_DOCS_FAMILY_SEARCH_AXUM_PATH,
            get(handlers::docs::projection::family::context::family_search),
        )
        .route(
            openapi_paths::API_DOCS_FAMILY_CLUSTER_AXUM_PATH,
            get(handlers::docs::projection::family::cluster::family_cluster),
        )
        .route(
            openapi_paths::API_DOCS_NAVIGATION_AXUM_PATH,
            get(handlers::docs::projection::navigation::routes::navigation),
        )
        .route(
            openapi_paths::API_DOCS_NAVIGATION_SEARCH_AXUM_PATH,
            get(handlers::docs::projection::navigation::routes::navigation_search),
        )
        .route(
            openapi_paths::API_UI_CAPABILITIES_AXUM_PATH,
            get(handlers::capabilities::get),
        )
        .route(
            openapi_paths::API_UI_PLUGIN_ARTIFACT_AXUM_PATH,
            get(handlers::capabilities::get_plugin_artifact),
        )
        .route(
            "/api/analysis/refine-doc",
            post(handlers::repo::refine::refine_entity_doc),
        )
        .route(
            "/api/document-extract-result",
            get(handlers::document_extract_result::get_document_extract_result),
        )
        .route(
            "/api/document-extract-resource",
            get(handlers::document_extract_resource::get_document_extract_resource),
        )
        .route(
            "/api/document-extract-jobs",
            get(handlers::document_extract_jobs::get_document_extract_jobs_status)
                .post(handlers::document_extract_jobs::submit_document_extract_job),
        )
        .route(
            "/api/document-extract-job",
            get(handlers::document_extract_jobs::get_document_extract_job),
        )
        .route(
            handlers::episteme::EPISTEME_SOURCE_CONTRACT_RUN_PLAN_ROUTE,
            post(handlers::episteme::plan_episteme_extraction_run),
        )
        .route(
            handlers::episteme::EPISTEME_EVIDENCE_READ_ROUTE,
            post(handlers::episteme::read_episteme_evidence_source),
        )
        .route(
            handlers::episteme::EPISTEME_EVIDENCE_SELECTION_PLAN_ROUTE,
            post(handlers::episteme::write_episteme_evidence_selection_plan_source),
        )
        .route(
            handlers::episteme::EPISTEME_ONTOLOGY_REGISTRY_READ_MODEL_ROUTE,
            post(handlers::episteme::admit_episteme_ontology_registry_read_model),
        )
        .route(
            openapi_paths::API_REPO_OVERVIEW_AXUM_PATH,
            get(handlers::repo::analysis::overview::overview),
        )
        .route(
            openapi_paths::API_REPO_MODULE_SEARCH_AXUM_PATH,
            get(handlers::repo::analysis::search::module::module_search),
        )
        .route(
            openapi_paths::API_REPO_SYMBOL_SEARCH_AXUM_PATH,
            get(handlers::repo::analysis::search::symbol::symbol_search),
        )
        .route(
            openapi_paths::API_REPO_EXAMPLE_SEARCH_AXUM_PATH,
            get(handlers::repo::analysis::search::example::example_search),
        )
        .route(
            openapi_paths::API_REPO_IMPORT_SEARCH_AXUM_PATH,
            get(handlers::repo::analysis::search::import::import_search),
        )
        .route(
            openapi_paths::API_REPO_DOC_COVERAGE_AXUM_PATH,
            get(handlers::repo::analysis::doc_coverage::doc_coverage),
        )
        .route(
            openapi_paths::API_REPO_INDEX_STATUS_AXUM_PATH,
            get(handlers::repo::index::repo_index_status),
        )
        .route(
            openapi_paths::API_REPO_INDEX_AXUM_PATH,
            post(handlers::repo::index::repo_index),
        )
        .route(
            openapi_paths::API_REPO_SYNC_AXUM_PATH,
            get(handlers::repo::analysis::sync::sync),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGES_AXUM_PATH,
            get(handlers::repo::pages::collection::projected_pages),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_GAP_REPORT_AXUM_PATH,
            get(handlers::repo::pages::collection::repo_projected_gap_report),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_AXUM_PATH,
            get(handlers::repo::pages::page::projected_page),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_INDEX_NODE_AXUM_PATH,
            get(handlers::repo::pages::page_index::projected_page_index_node),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_RETRIEVAL_HIT_AXUM_PATH,
            get(handlers::repo::retrieval::context::projected_retrieval_hit),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_RETRIEVAL_CONTEXT_AXUM_PATH,
            get(handlers::repo::retrieval::context::projected_retrieval_context),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_FAMILY_CONTEXT_AXUM_PATH,
            get(handlers::repo::family::context::projected_page_family_context),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_FAMILY_SEARCH_AXUM_PATH,
            get(handlers::repo::family::context::projected_page_family_search),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_FAMILY_CLUSTER_AXUM_PATH,
            get(handlers::repo::family::context::projected_page_family_cluster),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_NAVIGATION_AXUM_PATH,
            get(handlers::repo::family::navigation::projected_page_navigation),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_NAVIGATION_SEARCH_AXUM_PATH,
            get(handlers::repo::family::navigation::projected_page_navigation_search),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_INDEX_TREE_AXUM_PATH,
            get(handlers::repo::pages::page_index::projected_page_index_tree),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_INDEX_TREE_SEARCH_AXUM_PATH,
            get(handlers::repo::retrieval::search::projected_page_index_tree_search),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_SEARCH_AXUM_PATH,
            get(handlers::repo::retrieval::search::projected_page_search),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_RETRIEVAL_AXUM_PATH,
            get(handlers::repo::retrieval::search::projected_retrieval),
        )
        .route(
            openapi_paths::API_REPO_PROJECTED_PAGE_INDEX_TREES_AXUM_PATH,
            get(handlers::repo::pages::collection::projected_page_index_trees),
        )
}

/// Create the Studio API router with state already attached.
pub fn studio_router(state: Arc<GatewayState>) -> Router {
    studio_routes().with_state(state)
}
